import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {applyCurrentSchema} from './helpers/schema.mjs';
import worker from '../src/worker.js';

const ROOT=new URL('../',import.meta.url);
const STAFF=readFileSync(new URL('../public/staff/staff.js',import.meta.url),'utf8');
const CUSTOMER=readFileSync(new URL('../public/assets/app.js',import.meta.url),'utf8');
const STAFF_SERVER=readFileSync(new URL('../src/staff.js',import.meta.url),'utf8');
const OPS=readFileSync(new URL('../src/ops.js',import.meta.url),'utf8');
const MGMT=readFileSync(new URL('../src/management.js',import.meta.url),'utf8');
const SETTINGS=readFileSync(new URL('../src/settings.js',import.meta.url),'utf8');
const MAIN=readFileSync(new URL('../android/app/src/main/java/vn/lotusai/pos/phattaiapp/MainActivity.java',import.meta.url),'utf8');
const CONNECT=readFileSync(new URL('../android/app/src/main/java/vn/lotusai/pos/phattaiapp/CloudConnectivityActivity.java',import.meta.url),'utf8');
const DIAG=readFileSync(new URL('../android/app/src/main/java/vn/lotusai/pos/phattaiapp/DiagnosticsActivity.java',import.meta.url),'utf8');
const MANIFEST=readFileSync(new URL('../android/app/src/main/AndroidManifest.xml',import.meta.url),'utf8');
const APK_STAFF=readFileSync(new URL('../android/app/src/main/assets/staff/staff.js',import.meta.url),'utf8');

function fixture(){
 const db=new DatabaseSync(':memory:');
 applyCurrentSchema(db);
 db.exec('UPDATE pos_product_inventory SET stock=100; UPDATE pos_ingredients SET stock=100000;');
 const DB={prepare(sql){let args=[];return {bind(...v){args=v;return this},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:r.changes}}},_run(){return db.prepare(sql).run(...args)}}},async batch(statements){db.exec('BEGIN');try{const out=statements.map(s=>s._run());db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}};
 const env={DB,ASSETS:{fetch:async()=>new Response('not found',{status:404})},ORDERING_ENABLED:'true',ALLOW_UNVERIFIED_MEMBER_VOUCHERS:'true',SESSION_SECRET:'phattai-test-secret-012345678901234567890123',POS_STAFF_PASSWORD:'phattai-test-password'};
 const call=async(path,method='GET',body=null,headers={})=>{const h={Origin:'https://pos-phattai.test',...headers};if(body!==null&&!('Content-Type' in h))h['Content-Type']='application/json';const r=await worker.fetch(new Request('https://pos-phattai.test'+path,{method,headers:h,body:body===null?undefined:(typeof body==='string'?body:JSON.stringify(body))}),env);const ct=r.headers.get('content-type')||'';return {status:r.status,data:ct.includes('json')?await r.json():await r.text(),headers:r.headers}};
 return {db,env,call};
}
async function ownerAuth(call){const r=await call('/api/staff/login','POST',{username:'huang',password:'phattai-test-password'});assert.equal(r.status,200,JSON.stringify(r.data));return {Authorization:'Bearer '+r.data.token};}
function sha(x){return createHash('sha256').update(x).digest('hex')}
function roleAuth(fx,role='CASHIER'){
 const id=crypto.randomUUID(),token=('tok_'+role.toLowerCase()+'_'+id.replaceAll('-','')).slice(0,70),username=(role.toLowerCase()+'_'+id.slice(0,8));
 const at=new Date().toISOString();
 fx.db.prepare('INSERT INTO pos_staff_users(id,username,display_name,role_id,password_salt,password_hash,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,username,role+' QA',role,'dummy','dummy',1,at,at);
 fx.db.prepare('INSERT INTO pos_staff_sessions(token_hash,expires_at,staff_id) VALUES(?,?,?)').run(sha(token),Date.now()+3600000,id);
 return {Authorization:'Bearer '+token};
}
async function createOrder(fx,{table='T01',productId='101',qty=1,size='中',spice='中',note='',idem=crypto.randomUUID().replaceAll('-',''),items=null}={}){
 const payload={table,idempotencyKey:'qa_'+idem,items:items||[{productId,qty,mods:{size,spice,note}}],note};
 return fx.call('/api/orders','POST',payload);
}
async function detail(fx,auth,id){return fx.call('/api/staff/orders/'+id,'GET',null,auth)}
async function pay(fx,auth,id,version,method='CASH',received){const body={version,method};if(method==='CASH')body.received=received;return fx.call('/api/staff/orders/'+id+'/pay','POST',body,auth)}
function t(id,name,fn){test(`${id} ${name}`,fn)}

// ---------------------------------------------------------------------------
// GROUP A — 60 regression cases only for v1.5.2 additions/fixes.
// ---------------------------------------------------------------------------
const A=[];
A.push(['A01','huang authenticates as OWNER',async()=>{const fx=fixture();const a=await ownerAuth(fx.call);const me=await fx.call('/api/staff/me','GET',null,a);assert.equal(me.data.staff.role,'OWNER');fx.db.close()}]);
A.push(['A02','OWNER can load daily report',async()=>{const fx=fixture();const a=await ownerAuth(fx.call);const r=await fx.call('/api/staff/reports/daily?date=2026-09-28','GET',null,a);assert.equal(r.status,200);assert.equal(r.data.report.date,'2026-09-28');fx.db.close()}]);
A.push(['A03','cashier is blocked from daily report',async()=>{const fx=fixture();const a=roleAuth(fx,'CASHIER');const r=await fx.call('/api/staff/reports/daily?date=2026-09-28','GET',null,a);assert.equal(r.status,403);assert.equal(r.data.code,'OWNER_ONLY');fx.db.close()}]);
A.push(['A04','OWNER can load analytics report',async()=>{const fx=fixture();const a=await ownerAuth(fx.call);const r=await fx.call('/api/staff/reports/analytics?date=2026-09-28','GET',null,a);assert.equal(r.status,200);assert.ok(r.data.analytics);fx.db.close()}]);
A.push(['A05','manager is blocked from analytics report',async()=>{const fx=fixture();const a=roleAuth(fx,'MANAGER');const r=await fx.call('/api/staff/reports/analytics?date=2026-09-28','GET',null,a);assert.equal(r.status,403);fx.db.close()}]);
A.push(['A06','OWNER can read store/bank configuration',async()=>{const fx=fixture();const a=await ownerAuth(fx.call);const r=await fx.call('/api/staff/store','GET',null,a);assert.equal(r.status,200);assert.equal(r.data.store.name,'TIỆM SÍU LẬP PHÁT TÀI');assert.equal(r.data.store.bankBin,'970422');assert.equal(r.data.store.bankAccount,'00706885602');assert.equal(r.data.store.bankLabel,'MB');fx.db.close()}]);
A.push(['A07','non-owner cannot read store/bank configuration',async()=>{const fx=fixture();const a=roleAuth(fx,'MANAGER');const r=await fx.call('/api/staff/store','GET',null,a);assert.equal(r.status,403);assert.equal(r.data.code,'OWNER_ONLY');fx.db.close()}]);
A.push(['A08','store update rejects tableCount 0',async()=>{const fx=fixture();const a=await ownerAuth(fx.call);const s=(await fx.call('/api/staff/store','GET',null,a)).data.store;const r=await fx.call('/api/staff/store','PUT',{storeName:s.name,storeNameCn:s.nameCn,address:s.address,taxNumber:s.taxNumber,tableCount:0,bankLabel:s.bankLabel,bankBin:s.bankBin,bankAccount:s.bankAccount,bankName:s.bankName,transferPrefix:s.transferPrefix,taxMode:s.taxMode,taxRate:s.taxRate,githubUrl:s.githubUrl,feedbackUrl:s.feedbackUrl||'',version:s.version},a);assert.equal(r.status,400);fx.db.close()}]);
A.push(['A09','store update detects stale version',async()=>{const fx=fixture();const a=await ownerAuth(fx.call);const s=(await fx.call('/api/staff/store','GET',null,a)).data.store;const body={storeName:s.name,storeNameCn:s.nameCn,address:s.address,taxNumber:s.taxNumber,tableCount:s.tableCount,bankLabel:s.bankLabel,bankBin:s.bankBin,bankAccount:s.bankAccount,bankName:s.bankName,transferPrefix:s.transferPrefix,taxMode:s.taxMode,taxRate:s.taxRate,githubUrl:s.githubUrl,feedbackUrl:s.feedbackUrl||'',version:s.version};const one=await fx.call('/api/staff/store','PUT',body,a);assert.equal(one.status,200);const two=await fx.call('/api/staff/store','PUT',body,a);assert.equal(two.status,409);assert.equal(two.data.code,'STORE_CHANGED');fx.db.close()}]);
A.push(['A10','OWNER can list roles',async()=>{const fx=fixture();const a=await ownerAuth(fx.call);const r=await fx.call('/api/staff/roles','GET',null,a);assert.equal(r.status,200);assert.equal(r.data.roles.length,4);fx.db.close()}]);
A.push(['A11','cashier cannot list roles',async()=>{const fx=fixture();const a=roleAuth(fx,'CASHIER');const r=await fx.call('/api/staff/roles','GET',null,a);assert.equal(r.status,403);fx.db.close()}]);
A.push(['A12','OWNER can list staff accounts',async()=>{const fx=fixture();const a=await ownerAuth(fx.call);const r=await fx.call('/api/staff/accounts','GET',null,a);assert.equal(r.status,200);assert.ok(Array.isArray(r.data.accounts));fx.db.close()}]);
A.push(['A13','manager cannot list staff accounts',async()=>{const fx=fixture();const a=roleAuth(fx,'MANAGER');const r=await fx.call('/api/staff/accounts','GET',null,a);assert.equal(r.status,403);fx.db.close()}]);
A.push(['A14','OWNER can list voucher administration',async()=>{const fx=fixture();const a=await ownerAuth(fx.call);const r=await fx.call('/api/staff/vouchers','GET',null,a);assert.equal(r.status,200);assert.ok(Array.isArray(r.data.vouchers));fx.db.close()}]);
A.push(['A15','manager cannot access voucher administration',async()=>{const fx=fixture();const a=roleAuth(fx,'MANAGER');const r=await fx.call('/api/staff/vouchers','GET',null,a);assert.equal(r.status,403);fx.db.close()}]);
A.push(['A16','OWNER can create a CASHIER account',async()=>{const fx=fixture();const a=await ownerAuth(fx.call);const r=await fx.call('/api/staff/accounts','POST',{username:'cashierqa',name:'Cashier QA',password:'1234567890ab',role:'CASHIER'},a);assert.equal(r.status,201,JSON.stringify(r.data));assert.equal(r.data.account.role,'CASHIER');fx.db.close()}]);
A.push(['A17','OWNER cannot create second OWNER account through staff API',async()=>{const fx=fixture();const a=await ownerAuth(fx.call);const r=await fx.call('/api/staff/accounts','POST',{username:'otherowner',name:'Other Owner',password:'1234567890ab',role:'OWNER'},a);assert.equal(r.status,400);fx.db.close()}]);
A.push(['A18','OWNER system role is protected from role edits',async()=>{const fx=fixture();const a=await ownerAuth(fx.call);const r=await fx.call('/api/staff/roles/OWNER','PATCH',{name:'X',permissions:[],active:true},a);assert.equal(r.status,403);assert.equal(r.data.code,'OWNER_PROTECTED');fx.db.close()}]);
A.push(['A19','staff handheld navigation consolidates OWNER tools under one parent',()=>{assert.match(STAFF,/\['owner','Quản trị chủ tiệm \/ 店主管理'/);assert.match(STAFF,/function ownerAdminScreen\(\)/)}]);
A.push(['A20','owner hub exposes store management as a child action',()=>assert.match(STAFF,/\['store','Quản lý tiệm','门店管理'/)]);
A.push(['A21','owner hub exposes account and permission management as a child action',()=>assert.match(STAFF,/\['team','Tài khoản & quyền','账号与权限'/)]);
A.push(['A22','owner hub exposes device and printer administration',()=>assert.match(STAFF,/\['settings','Thiết bị & máy in','设备与打印机'/)]);
A.push(['A23','CSV daily report and SUNMI print actions exist',()=>{assert.match(STAFF,/data-action="report-download"/);assert.match(STAFF,/In SUNMI \/ SUNMI 打印/);assert.match(STAFF,/BÁO CÁO CA \/ 班次报表/)}]);
A.push(['A24','SUNMI daily report print action is owner-gated',()=>assert.match(STAFF,/if\(!isOwner\(\)\)throw Error\('Chỉ chủ tiệm được in báo cáo/)]);
A.push(['A25','SUNMI daily report print requires native bridge',()=>assert.match(STAFF,/native\?\.printDailyReport/)]);
A.push(['A26','hardware settings actions re-fetch current staff identity',()=>assert.match(STAFF,/\['kitchen-config','kitchen-jobs','device-check','sunmi-check','sunmi-reconnect'\][\s\S]*api\('GET','\/api\/staff\/me'\)/)]);
A.push(['A27','hardware settings actions enforce OWNER at UI layer',()=>assert.match(STAFF,/Chỉ chủ tiệm được cấu hình và kiểm tra phần cứng/)]);
A.push(['A28','hardware settings actions enforce APK/native environment',()=>assert.match(STAFF,/Chức năng phần cứng chỉ có trong APK SUNMI/)]);
A.push(['A29','kitchen configuration action calls native.openKitchenSettings',()=>assert.match(STAFF,/action==='kitchen-config'\)native\.openKitchenSettings\(\)/)]);
A.push(['A30','kitchen jobs action calls native.openKitchenJobs',()=>assert.match(STAFF,/action==='kitchen-jobs'\)native\.openKitchenJobs\(\)/)]);
A.push(['A31','device diagnostics action calls native.openDiagnostics',()=>assert.match(STAFF,/action==='device-check'\)native\.openDiagnostics\(\)/)]);
A.push(['A32','SUNMI printer check action calls native.checkPrinter',()=>assert.match(STAFF,/action==='sunmi-check'\)native\.checkPrinter/)]);
A.push(['A33','SUNMI reconnect action calls native.reconnectPrinter',()=>assert.match(STAFF,/else native\.reconnectPrinter\(\)/)]);
A.push(['A34','Android connectivity screen exposes kitchen printer IP input',()=>assert.match(CONNECT,/IP máy in bếp/)]);
A.push(['A35','Android connectivity screen exposes numeric kitchen printer port',()=>{assert.match(CONNECT,/Cổng, thường là 9100/);assert.match(CONNECT,/TYPE_CLASS_NUMBER/)}]);
A.push(['A36','Android connectivity screen persists kitchen LAN settings',()=>assert.match(CONNECT,/lotus_kitchen_lan/)]);
A.push(['A37','Android connectivity screen exposes kitchen test print/settings',()=>assert.match(CONNECT,/Cài đặt \/ in thử phiếu bếp/)]);
A.push(['A38','Android connectivity screen exposes SUNMI diagnostics',()=>assert.match(CONNECT,/Mở kiểm tra SUNMI/)]);
A.push(['A39','Diagnostics activity binds SUNMI printer service',()=>assert.match(DIAG,/InnerPrinterManager\.getInstance\(\)\.bindService/)]);
A.push(['A40','Diagnostics activity reads current printer state',()=>assert.match(DIAG,/updatePrinterState\(\)/)]);
A.push(['A41','native receipt bridge submits RECEIPT type',()=>assert.match(MAIN,/printReceipt\(String id,String payload\)[\s\S]{0,120}submitPrint\(id,"RECEIPT",payload\)/)]);
A.push(['A42','native kitchen bridge is separate LAN path',()=>assert.match(MAIN,/printKitchen\(String id,String payload\)[\s\S]{0,140}kitchen\.submit\(id,payload\)/)]);
A.push(['A43','native daily report print bridge exists',()=>assert.match(MAIN,/printDailyReport\(String id,String (?:payload|raw)\)/)]);
A.push(['A44','customer order commit creates exactly one kitchen job immediately',async()=>{const fx=fixture();const c=await createOrder(fx);assert.equal(c.status,201);assert.equal(fx.db.prepare('SELECT COUNT(*) n FROM pos_kitchen_jobs WHERE order_id=?').get(c.data.order.id).n,1);fx.db.close()}]);
A.push(['A45','unpaid order is visible in automatic kitchen queue',async()=>{const fx=fixture();const c=await createOrder(fx);const a=await ownerAuth(fx.call);const q=await fx.call('/api/staff/paid-labels','GET',null,a);assert.ok(q.data.jobs.some(j=>j.order.id===c.data.order.id));fx.db.close()}]);
A.push(['A46','kitchen job can be claimed before payment',async()=>{const fx=fixture();const c=await createOrder(fx);const a=await ownerAuth(fx.call);const q=await fx.call('/api/staff/paid-labels','GET',null,a);const j=q.data.jobs.find(x=>x.order.id===c.data.order.id);const r=await fx.call('/api/staff/jobs/'+encodeURIComponent(j.id)+'/claim','POST',{},a);assert.equal(r.status,200);assert.equal(r.data.status,'CLAIMED');fx.db.close()}]);
A.push(['A47','BANK payment does not create a second kitchen job',async()=>{const fx=fixture();const c=await createOrder(fx);const a=await ownerAuth(fx.call);const d=await detail(fx,a,c.data.order.id);const p=await pay(fx,a,c.data.order.id,d.data.order.version,'BANK');assert.equal(p.status,200);assert.equal(fx.db.prepare('SELECT COUNT(*) n FROM pos_kitchen_jobs WHERE order_id=?').get(c.data.order.id).n,1);fx.db.close()}]);
A.push(['A48','CASH payment does not create a second kitchen job',async()=>{const fx=fixture();const c=await createOrder(fx);const a=await ownerAuth(fx.call);const d=await detail(fx,a,c.data.order.id);const p=await pay(fx,a,c.data.order.id,d.data.order.version,'CASH',d.data.order.total+10000);assert.equal(p.status,200);assert.equal(fx.db.prepare('SELECT COUNT(*) n FROM pos_kitchen_jobs WHERE order_id=?').get(c.data.order.id).n,1);fx.db.close()}]);
A.push(['A49','paid order disappears from automatic kitchen queue',async()=>{const fx=fixture();const c=await createOrder(fx);const a=await ownerAuth(fx.call);const d=await detail(fx,a,c.data.order.id);await pay(fx,a,c.data.order.id,d.data.order.version,'BANK');const q=await fx.call('/api/staff/paid-labels','GET',null,a);assert.equal(q.data.jobs.some(j=>j.order.id===c.data.order.id),false);fx.db.close()}]);
A.push(['A50','stale PENDING kitchen job cannot be claimed after payment',async()=>{const fx=fixture();const c=await createOrder(fx);const a=await ownerAuth(fx.call);const j=fx.db.prepare('SELECT id FROM pos_kitchen_jobs WHERE order_id=?').get(c.data.order.id);const d=await detail(fx,a,c.data.order.id);await pay(fx,a,c.data.order.id,d.data.order.version,'BANK');fx.db.prepare("UPDATE pos_kitchen_jobs SET status='PENDING' WHERE id=?").run(j.id);const r=await fx.call('/api/staff/jobs/'+encodeURIComponent(j.id)+'/claim','POST',{},a);assert.equal(r.status,409);fx.db.close()}]);
A.push(['A51','stale paid kitchen job status cannot be advanced after payment',async()=>{const fx=fixture();const c=await createOrder(fx);const a=await ownerAuth(fx.call);const j=fx.db.prepare('SELECT id FROM pos_kitchen_jobs WHERE order_id=?').get(c.data.order.id);const d=await detail(fx,a,c.data.order.id);await pay(fx,a,c.data.order.id,d.data.order.version,'BANK');const r=await fx.call('/api/staff/jobs/'+encodeURIComponent(j.id)+'/status','POST',{status:'SENT'},a);assert.equal(r.status,409);fx.db.close()}]);
A.push(['A52','BANK payment finalizes order code with CK',async()=>{const fx=fixture();const c=await createOrder(fx);const a=await ownerAuth(fx.call);const d=await detail(fx,a,c.data.order.id);const p=await pay(fx,a,c.data.order.id,d.data.order.version,'BANK');assert.match(p.data.order.code,/-CK$/);fx.db.close()}]);
A.push(['A53','CASH payment finalizes order code with TM',async()=>{const fx=fixture();const c=await createOrder(fx);const a=await ownerAuth(fx.call);const d=await detail(fx,a,c.data.order.id);const p=await pay(fx,a,c.data.order.id,d.data.order.version,'CASH',d.data.order.total);assert.match(p.data.order.code,/-TM$/);fx.db.close()}]);
A.push(['A54','CASH payment records correct change',async()=>{const fx=fixture();const c=await createOrder(fx);const a=await ownerAuth(fx.call);const d=await detail(fx,a,c.data.order.id);const p=await pay(fx,a,c.data.order.id,d.data.order.version,'CASH',d.data.order.total+22000);assert.equal(p.data.order.cashChange,22000);fx.db.close()}]);
A.push(['A55','staff payment success invokes receipt bridge and refreshes paid detail',()=>{assert.match(STAFF,/printReceipt\(r\.order,paidBill\)/);assert.match(STAFF,/st\.detail=r/)}]);
A.push(['A56','staff payment success message is bilingual and states kitchen is not reprinted',()=>assert.match(STAFF,/Đã gửi biên lai tới máy in SUNMI \/ 已发送收据至 SUNMI；phiếu bếp không in lại \/ 厨房单不会重复打印/)]);
A.push(['A57','paid kitchen card removes normal kitchen print action',()=>assert.match(STAFF,/paid\?`<p class="muted">Phiếu bếp này thuộc thời điểm chốt order[\s\S]*Đã kiểm tra phiếu giấy/)]);
// v1.5.3 UI regressions are folded into the 60-case v1.5.x group without increasing case count.
A.push(['A58','source includes refund form, styled modifier dialog and bilingualizer regressions',()=>{assert.match(STAFF,/function refundForm\(/);assert.match(STAFF,/class="item-overlay"/);assert.match(STAFF,/function bilingualize\(/)}]);
A.push(['A59','Android source exposes separate receipt, kitchen and owner hardware bridge methods',()=>{for(const s of ['printReceipt','printKitchen','printDailyReport','openKitchenSettings','openKitchenJobs','openDiagnostics','checkPrinter','reconnectPrinter','RECEIPT'])assert.ok(MAIN.includes(s),s)}]);
A.push(['A60','Android Java namespace is explicit and separate from the install profile',()=>{assert.match(MANIFEST,/vn\.lotusai\.pos\.phattaiapp/);assert.doesNotMatch(MANIFEST,/vn\.lotusai\.pos\.handheld/)}]);

// ---------------------------------------------------------------------------
// GROUP B — 60 end-to-end/business cases across Customer QR + Staff/SUNMI UI.
// ---------------------------------------------------------------------------
const B=[];
B.push(['B01','catalog exposes exactly 19 active PHAT TAI menu items',async()=>{const fx=fixture();const r=await fx.call('/api/catalog');assert.equal(r.status,200);assert.equal(r.data.catalog.products.filter(p=>p.active).length,19);assert.ok(r.data.catalog.products.every(p=>p.sku.startsWith('PT')));fx.db.close()}]);
B.push(['B02','customer UI starts with table picker requirement',()=>{assert.match(CUSTOMER,/tablePicker:true/);assert.match(CUSTOMER,/Chọn bàn/)}]);
B.push(['B03','valid T01 order is accepted',async()=>{const fx=fixture();const r=await createOrder(fx,{table:'T01'});assert.equal(r.status,201);assert.equal(r.data.order.table,'T01');fx.db.close()}]);
B.push(['B04','valid T99 order is accepted at configured table limit',async()=>{const fx=fixture();const r=await createOrder(fx,{table:'T99'});assert.equal(r.status,201);assert.equal(r.data.order.table,'T99');fx.db.close()}]);
B.push(['B05','table above configured limit is rejected',async()=>{const fx=fixture();const r=await createOrder(fx,{table:'T100'});assert.equal(r.status,400);assert.equal(r.data.code,'INVALID_TABLE');fx.db.close()}]);
B.push(['B06','malformed table is rejected',async()=>{const fx=fixture();const r=await createOrder(fx,{table:'ABC'});assert.equal(r.status,400);fx.db.close()}]);
B.push(['B07','TAKEAWAY order remains supported',async()=>{const fx=fixture();const r=await createOrder(fx,{table:'TAKEAWAY'});assert.equal(r.status,201);assert.equal(r.data.order.table,'TAKEAWAY');fx.db.close()}]);
B.push(['B08','empty customer cart is rejected',async()=>{const fx=fixture();const r=await fx.call('/api/orders','POST',{table:'T01',idempotencyKey:'qa_empty_cart_0001',items:[]});assert.equal(r.status,400);assert.equal(r.data.code,'INVALID_CART');fx.db.close()}]);
B.push(['B09','more than 30 cart lines are rejected',async()=>{const fx=fixture();const items=Array.from({length:31},()=>({productId:'101',qty:1,mods:{size:'中',spice:'中'}}));const r=await createOrder(fx,{items});assert.equal(r.status,400);assert.equal(r.data.code,'INVALID_CART');fx.db.close()}]);
B.push(['B10','quantity over 30 on one line is rejected',async()=>{const fx=fixture();const r=await createOrder(fx,{qty:31});assert.equal(r.status,400);assert.equal(r.data.code,'INVALID_QUANTITY');fx.db.close()}]);
B.push(['B11','total units over 60 are rejected',async()=>{const fx=fixture();const items=[{productId:'101',qty:30,mods:{size:'中',spice:'中'}},{productId:'102',qty:30,mods:{size:'中',spice:'中'}},{productId:'103',qty:1,mods:{size:'中',spice:'中'}}];const r=await createOrder(fx,{items});assert.equal(r.status,400);assert.equal(r.data.code,'TOO_MANY_ITEMS');fx.db.close()}]);
B.push(['B12','invalid size option is rejected',async()=>{const fx=fixture();const r=await createOrder(fx,{size:'S'});assert.equal(r.status,400);assert.equal(r.data.code,'INVALID_SIZE');fx.db.close()}]);
B.push(['B13','invalid spicy option is rejected',async()=>{const fx=fixture();const r=await createOrder(fx,{spice:'SIÊU CAY'});assert.equal(r.status,400);assert.equal(r.data.code,'INVALID_SPICE');fx.db.close()}]);
B.push(['B14','inactive menu product cannot be ordered',async()=>{const fx=fixture();fx.db.prepare("UPDATE pos_products SET active=0 WHERE id='101'").run();const r=await createOrder(fx);assert.equal(r.status,400);assert.equal(r.data.code,'UNAVAILABLE_PRODUCT');fx.db.close()}]);
B.push(['B15','customer order is created UNPAID',async()=>{const fx=fixture();const r=await createOrder(fx);assert.equal(r.data.order.paymentStatus,'UNPAID');assert.equal(r.data.order.status,'ACCEPTED');fx.db.close()}]);
B.push(['B16','customer response never exposes bank payment QR',async()=>{const fx=fixture();const r=await createOrder(fx);assert.equal('bankPayment' in r.data.order,false);fx.db.close()}]);
B.push(['B17','customer order code is base format before payment',async()=>{const fx=fixture();const r=await createOrder(fx);assert.match(r.data.order.code,/^\d{8}-\d{4}-[0-9A-F]{6}$/);fx.db.close()}]);
B.push(['B18','same idempotency key returns same order without duplicate',async()=>{const fx=fixture();const idem='same_order_key_0001';const one=await createOrder(fx,{idem});const two=await createOrder(fx,{idem});assert.equal(one.status,201);assert.equal(two.status,200);assert.equal(two.data.duplicate,true);assert.equal(two.data.order.id,one.data.order.id);assert.equal(fx.db.prepare('SELECT COUNT(*) n FROM qr_orders').get().n,1);fx.db.close()}]);
B.push(['B19','reusing idempotency key with different cart is rejected',async()=>{const fx=fixture();const idem='reuse_conflict_0001';await createOrder(fx,{idem,productId:'101'});const two=await createOrder(fx,{idem,productId:'102'});assert.equal(two.status,409);assert.equal(two.data.code,'REQUEST_ID_REUSED');fx.db.close()}]);
B.push(['B20','customer can read own order using order token',async()=>{const fx=fixture();const c=await createOrder(fx);const r=await fx.call('/api/orders/'+c.data.order.id,'GET',null,{'x-order-token':c.data.orderToken});assert.equal(r.status,200);assert.equal(r.data.order.id,c.data.order.id);fx.db.close()}]);
B.push(['B21','wrong customer order token is denied',async()=>{const fx=fixture();const c=await createOrder(fx);const r=await fx.call('/api/orders/'+c.data.order.id,'GET',null,{'x-order-token':'wrong-token'});assert.equal(r.status,403);fx.db.close()}]);
B.push(['B22','customer can request staff service for an open order',async()=>{const fx=fixture();const c=await createOrder(fx);const r=await fx.call('/api/orders/'+c.data.order.id+'/service','POST',{}, {'x-order-token':c.data.orderToken});assert.equal(r.status,200);assert.equal(r.data.requestPending,true);fx.db.close()}]);
B.push(['B23','service request is idempotent while pending',async()=>{const fx=fixture();const c=await createOrder(fx);await fx.call('/api/orders/'+c.data.order.id+'/service','POST',{}, {'x-order-token':c.data.orderToken});await fx.call('/api/orders/'+c.data.order.id+'/service','POST',{}, {'x-order-token':c.data.orderToken});assert.equal(fx.db.prepare("SELECT COUNT(*) n FROM pos_service_requests WHERE order_id=? AND status='PENDING'").get(c.data.order.id).n,1);fx.db.close()}]);
B.push(['B24','staff order list contains QR-created order',async()=>{const fx=fixture();const c=await createOrder(fx,{table:'T12'});const a=await ownerAuth(fx.call);const r=await fx.call('/api/staff/orders','GET',null,a);assert.ok(r.data.orders.some(o=>o.id===c.data.order.id&&o.table==='T12'));fx.db.close()}]);
B.push(['B25','staff order detail contains table, items and total for reconciliation',async()=>{const fx=fixture();const c=await createOrder(fx,{table:'T15',productId:'110'});const a=await ownerAuth(fx.call);const r=await detail(fx,a,c.data.order.id);assert.equal(r.data.order.table,'T15');assert.equal(r.data.order.items.length,1);assert.equal(r.data.order.total,80000);fx.db.close()}]);
B.push(['B26','staff order detail exposes bank QR only to authenticated staff',async()=>{const fx=fixture();const c=await createOrder(fx);const a=await ownerAuth(fx.call);const r=await detail(fx,a,c.data.order.id);assert.ok(r.data.order.bankPayment?.payload);assert.equal(r.data.order.bankPayment.amount,r.data.order.total);fx.db.close()}]);
B.push(['B27','unauthenticated caller cannot access staff order detail',async()=>{const fx=fixture();const c=await createOrder(fx);const r=await detail(fx,{},c.data.order.id);assert.equal(r.status,401);fx.db.close()}]);
B.push(['B28','cashier role can view orders',async()=>{const fx=fixture();const c=await createOrder(fx);const a=roleAuth(fx,'CASHIER');const r=await detail(fx,a,c.data.order.id);assert.equal(r.status,200);fx.db.close()}]);
B.push(['B29','kitchen role cannot confirm payment',async()=>{const fx=fixture();const c=await createOrder(fx);const owner=await ownerAuth(fx.call);const d=await detail(fx,owner,c.data.order.id);const k=roleAuth(fx,'KITCHEN');const r=await pay(fx,k,c.data.order.id,d.data.order.version,'CASH',d.data.order.total);assert.equal(r.status,403);fx.db.close()}]);
B.push(['B30','cashier can confirm CASH payment',async()=>{const fx=fixture();const c=await createOrder(fx);const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const r=await pay(fx,a,c.data.order.id,d.data.order.version,'CASH',d.data.order.total);assert.equal(r.status,200);assert.equal(r.data.order.paymentStatus,'PAID');fx.db.close()}]);
B.push(['B31','cash payment below total is rejected',async()=>{const fx=fixture();const c=await createOrder(fx);const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const r=await pay(fx,a,c.data.order.id,d.data.order.version,'CASH',d.data.order.total-1);assert.equal(r.status,400);assert.equal(r.data.code,'CASH_INSUFFICIENT');fx.db.close()}]);
B.push(['B32','cash payment equal to total returns zero change',async()=>{const fx=fixture();const c=await createOrder(fx);const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const r=await pay(fx,a,c.data.order.id,d.data.order.version,'CASH',d.data.order.total);assert.equal(r.data.order.cashChange,0);fx.db.close()}]);
B.push(['B33','cash payment above total calculates positive change',async()=>{const fx=fixture();const c=await createOrder(fx);const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const r=await pay(fx,a,c.data.order.id,d.data.order.version,'CASH',d.data.order.total+50000);assert.equal(r.data.order.cashChange,50000);fx.db.close()}]);
B.push(['B34','BANK payment succeeds when bank configuration exists',async()=>{const fx=fixture();const c=await createOrder(fx);const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const r=await pay(fx,a,c.data.order.id,d.data.order.version,'BANK');assert.equal(r.status,200);assert.equal(r.data.order.paymentMethod,'BANK');fx.db.close()}]);
B.push(['B35','BANK payment is blocked when bank configuration is missing on order snapshot',async()=>{const fx=fixture();const c=await createOrder(fx);fx.db.prepare("UPDATE qr_orders SET bank_bin='',bank_account='',bank_name='' WHERE id=?").run(c.data.order.id);const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const r=await pay(fx,a,c.data.order.id,d.data.order.version,'BANK');assert.equal(r.status,409);assert.equal(r.data.code,'BANK_NOT_CONFIGURED');fx.db.close()}]);
B.push(['B36','same order cannot be paid twice',async()=>{const fx=fixture();const c=await createOrder(fx);const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const one=await pay(fx,a,c.data.order.id,d.data.order.version,'BANK');assert.equal(one.status,200);const two=await pay(fx,a,c.data.order.id,one.data.order.version,'BANK');assert.equal(two.status,409);fx.db.close()}]);
B.push(['B37','stale order version is rejected at payment',async()=>{const fx=fixture();const c=await createOrder(fx);const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const r=await pay(fx,a,c.data.order.id,d.data.order.version+10,'CASH',d.data.order.total);assert.equal(r.status,409);assert.equal(r.data.code,'ORDER_CHANGED');fx.db.close()}]);
B.push(['B38','customer cannot request service after order is paid',async()=>{const fx=fixture();const c=await createOrder(fx);const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);await pay(fx,a,c.data.order.id,d.data.order.version,'BANK');const r=await fx.call('/api/orders/'+c.data.order.id+'/service','POST',{}, {'x-order-token':c.data.orderToken});assert.equal(r.status,409);fx.db.close()}]);
B.push(['B39','kitchen queue exposes table and order code before payment',async()=>{const fx=fixture();const c=await createOrder(fx,{table:'T28'});const a=roleAuth(fx,'KITCHEN');const q=await fx.call('/api/staff/paid-labels','GET',null,a);const j=q.data.jobs.find(x=>x.order.id===c.data.order.id);assert.equal(j.order.table,'T28');assert.equal(j.order.code,c.data.order.code);fx.db.close()}]);
B.push(['B40','kitchen job can transition CLAIMED -> SENT while unpaid',async()=>{const fx=fixture();const c=await createOrder(fx);const a=roleAuth(fx,'KITCHEN');const q=await fx.call('/api/staff/paid-labels','GET',null,a);const j=q.data.jobs.find(x=>x.order.id===c.data.order.id);assert.equal((await fx.call('/api/staff/jobs/'+encodeURIComponent(j.id)+'/claim','POST',{},a)).status,200);const s=await fx.call('/api/staff/jobs/'+encodeURIComponent(j.id)+'/status','POST',{status:'SENT'},a);assert.equal(s.status,200);assert.equal(s.data.status,'SENT');fx.db.close()}]);
B.push(['B41','invalid kitchen job status is rejected',async()=>{const fx=fixture();const c=await createOrder(fx);const a=roleAuth(fx,'KITCHEN');const j=fx.db.prepare('SELECT id FROM pos_kitchen_jobs WHERE order_id=?').get(c.data.order.id);const r=await fx.call('/api/staff/jobs/'+encodeURIComponent(j.id)+'/status','POST',{status:'PAID'},a);assert.equal(r.status,400);fx.db.close()}]);
B.push(['B42','staff can append an item before payment',async()=>{const fx=fixture();const c=await createOrder(fx);const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const r=await fx.call('/api/staff/orders/'+c.data.order.id+'/append','POST',{version:d.data.order.version,table:d.data.order.table,items:[{productId:'110',qty:1,mods:{size:'中',spice:'中',note:'thêm'}}]},a);assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(r.data.order.items.length,2);fx.db.close()}]);
B.push(['B43','append increments kitchen revision and produces one delta ticket',async()=>{const fx=fixture();const c=await createOrder(fx);const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);await fx.call('/api/staff/orders/'+c.data.order.id+'/append','POST',{version:d.data.order.version,table:d.data.order.table,items:[{productId:'110',qty:1,mods:{size:'中',spice:'中',note:''}}]},a);assert.equal(fx.db.prepare('SELECT COUNT(*) n FROM pos_kitchen_jobs WHERE order_id=?').get(c.data.order.id).n,2);fx.db.close()}]);
B.push(['B44','staff can cancel one unit before payment with reason',async()=>{const fx=fixture();const c=await createOrder(fx,{qty:2});const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const r=await fx.call('/api/staff/orders/'+c.data.order.id+'/cancel-unit','POST',{version:d.data.order.version,index:0,reason:'khách đổi ý'},a);assert.equal(r.status,200);assert.equal(r.data.order.items[0].qty,1);fx.db.close()}]);
B.push(['B45','cancel-unit without reason is rejected',async()=>{const fx=fixture();const c=await createOrder(fx,{qty:2});const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const r=await fx.call('/api/staff/orders/'+c.data.order.id+'/cancel-unit','POST',{version:d.data.order.version,index:0,reason:''},a);assert.equal(r.status,400);assert.equal(r.data.code,'REASON_REQUIRED');fx.db.close()}]);
B.push(['B46','staff can cancel entire unpaid order with reason',async()=>{const fx=fixture();const c=await createOrder(fx);const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const r=await fx.call('/api/staff/orders/'+c.data.order.id+'/cancel','POST',{version:d.data.order.version,reason:'khách rời quán'},a);assert.equal(r.status,200);assert.equal(r.data.order.status,'CANCELLED');fx.db.close()}]);
B.push(['B47','cancelled order queues only the CANCEL kitchen ticket',async()=>{const fx=fixture();const c=await createOrder(fx);const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);await fx.call('/api/staff/orders/'+c.data.order.id+'/cancel','POST',{version:d.data.order.version,reason:'hủy'},a);const k=roleAuth(fx,'KITCHEN');const q=await fx.call('/api/staff/paid-labels','GET',null,k);const jobs=q.data.jobs.filter(j=>j.order.id===c.data.order.id);assert.equal(jobs.length,1);assert.equal(jobs[0].kind,'CANCEL');fx.db.close()}]);
B.push(['B48','split bill conserves order total across two bills',async()=>{const fx=fixture();const c=await createOrder(fx,{qty:2});const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const r=await fx.call('/api/staff/orders/'+c.data.order.id+'/split','POST',{version:d.data.order.version,parts:[[{index:0,qty:1}],[{index:0,qty:1}]]},a);assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(r.data.bills.length,2);assert.equal(r.data.bills.reduce((n,b)=>n+b.total,0),c.data.order.total);fx.db.close()}]);
B.push(['B49','invalid split that does not allocate all units is rejected',async()=>{const fx=fixture();const c=await createOrder(fx,{qty:2});const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const r=await fx.call('/api/staff/orders/'+c.data.order.id+'/split','POST',{version:d.data.order.version,parts:[[{index:0,qty:1}],[{index:0,qty:0}]]},a);assert.equal(r.status,400);fx.db.close()}]);
B.push(['B50','individual split bill can be paid CASH',async()=>{const fx=fixture();const c=await createOrder(fx,{qty:2});const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const s=await fx.call('/api/staff/orders/'+c.data.order.id+'/split','POST',{version:d.data.order.version,parts:[[{index:0,qty:1}],[{index:0,qty:1}]]},a);const b=s.data.bills[0];const r=await fx.call('/api/staff/bills/'+encodeURIComponent(b.id)+'/pay','POST',{method:'CASH',received:b.total},a);assert.equal(r.status,200);assert.equal(r.data.bills.find(x=>x.id===b.id).paymentStatus,'PAID');fx.db.close()}]);
B.push(['B51','individual split bill can be paid BANK',async()=>{const fx=fixture();const c=await createOrder(fx,{qty:2});const a=roleAuth(fx,'CASHIER');const d=await detail(fx,a,c.data.order.id);const s=await fx.call('/api/staff/orders/'+c.data.order.id+'/split','POST',{version:d.data.order.version,parts:[[{index:0,qty:1}],[{index:0,qty:1}]]},a);const b=s.data.bills[0];const r=await fx.call('/api/staff/bills/'+encodeURIComponent(b.id)+'/pay','POST',{method:'BANK'},a);assert.equal(r.status,200);assert.equal(r.data.bills.find(x=>x.id===b.id).paymentMethod,'BANK');fx.db.close()}]);
B.push(['B52','customer UI explicitly states payment is staff-handled',()=>assert.match(CUSTOMER,/Khách không thanh toán trên UI này/)]);
B.push(['B53','customer UI contains no payment-reported API path',()=>assert.doesNotMatch(CUSTOMER,/payment-reported/)]);
B.push(['B54','customer UI order button copy says D1 + kitchen ticket immediately',()=>assert.match(CUSTOMER,/Chốt order; hệ thống lưu D1 và gửi phiếu bếp ngay/)]);
B.push(['B55','staff UI requires table/order reconciliation before payment stage',()=>assert.match(STAFF,/ĐỐI CHIẾU BÀN/)]);
B.push(['B56','staff UI exposes both CASH and BANK payment choices',()=>{assert.match(STAFF,/data-choose-pay="CASH"/);assert.match(STAFF,/data-choose-pay="BANK"/)}]);
B.push(['B57','staff UI shows bank QR only during staff payment flow',()=>{assert.match(STAFF,/function bankCard/);assert.match(STAFF,/QR chuyển khoản/)}]);
B.push(['B58','staff scheduler preserves kitchen queue base cadence at 3 seconds',()=>assert.match(STAFF,/print:\{base:3000/)]);
B.push(['B59','Android assets contain the live Staff UI used by business payment flow',()=>{assert.ok(APK_STAFF.includes('data-choose-pay="CASH"'));assert.ok(APK_STAFF.includes('data-choose-pay="BANK"'));assert.ok(APK_STAFF.includes('printReceipt(r.order,paidBill)'))}]);
B.push(['B60','Android assets contain owner hardware/admin UI used during store operations',()=>{for(const s of ['Quản trị chủ tiệm','Báo cáo ngày','Tài khoản & quyền','IP / cổng máy in bếp','Kiểm tra toàn bộ phần cứng'])assert.ok(APK_STAFF.includes(s),s)}]);

assert.equal(A.length,60,'Group A must contain exactly 60 cases');
assert.equal(B.length,60,'Group B must contain exactly 60 cases');
for(const [id,name,fn] of A)t(id,name,fn);
for(const [id,name,fn] of B)t(id,name,fn);
