import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import worker,{RealtimeHub} from '../src/worker.js';
import {mutationScopes} from '../src/sync.js';
import {currentFixture} from './helpers/current-fixture.mjs';
const STAFF=readFileSync(new URL('../public/staff/staff.js',import.meta.url),'utf8');

test('SYNC metadata stays unchanged on read-only requests',async()=>{const f=currentFixture(),a=f.actor();try{const before=(await f.call('/api/staff/sync-meta','GET',null,a.headers)).data.revisions;await f.call('/api/staff/orders','GET',null,a.headers);assert.deepEqual((await f.call('/api/staff/sync-meta','GET',null,a.headers)).data.revisions,before)}finally{f.db.close()}});
test('SYNC a new order increments orders and print revisions transactionally',async()=>{const f=currentFixture(),a=f.actor();try{const before=(await f.call('/api/staff/sync-meta','GET',null,a.headers)).data.revisions;assert.equal((await f.order(a)).status,201);const after=(await f.call('/api/staff/sync-meta','GET',null,a.headers)).data.revisions;assert.ok(Number(after.orders)>Number(before.orders));assert.ok(Number(after.print)>Number(before.print));assert.equal(after.catalog,before.catalog)}finally{f.db.close()}});
test('SYNC catalog revision changes even if timestamps and product count do not',async()=>{const f=currentFixture();try{const before=(await f.call('/api/catalog/meta')).data.revision;f.db.prepare("UPDATE pos_products SET price=price+1000 WHERE id='101'").run();assert.notEqual((await f.call('/api/catalog/meta')).data.revision,before)}finally{f.db.close()}});
test('SYNC modifier edits invalidate catalog without a product edit',async()=>{const f=currentFixture();try{f.db.exec("INSERT INTO pos_menu_options(group_code,option_code,option_vi,option_zh,price_delta) VALUES('TOPPING','QA','QA','QA',1000)");const before=(await f.call('/api/catalog/meta')).data.revision;f.db.exec('UPDATE pos_menu_options SET price_delta=price_delta+1');assert.notEqual((await f.call('/api/catalog/meta')).data.revision,before)}finally{f.db.close()}});
test('SYNC rolled-back writes also roll back revision counters',async()=>{const f=currentFixture();try{const before=(await f.call('/api/catalog/meta')).data.revision;f.db.exec("BEGIN; UPDATE pos_products SET price=price+1000 WHERE id='101'; ROLLBACK;");assert.equal((await f.call('/api/catalog/meta')).data.revision,before)}finally{f.db.close()}});
test('SYNC metadata still requires an active staff session',async()=>{const f=currentFixture();try{assert.equal((await f.call('/api/staff/sync-meta')).status,401)}finally{f.db.close()}});
test('PRINT unchanged revision skips the heavy kitchen list query',async()=>{const f=currentFixture(),a=f.actor();try{await f.order(a);const first=await f.call('/api/staff/paid-labels','GET',null,a.headers);assert.equal(first.data.jobs.length,1);f.queries.length=0;const next=await f.call('/api/staff/paid-labels?revision='+encodeURIComponent(first.data.revision),'GET',null,a.headers);assert.equal(next.data.unchanged,true);assert.deepEqual(next.data.jobs,[]);assert.ok(!f.queries.some(sql=>sql.includes('JOIN pos_auto_print_config')))}finally{f.db.close()}});
test('PRINT changed queue revision returns new jobs instead of unchanged',async()=>{const f=currentFixture(),a=f.actor();try{const first=await f.call('/api/staff/paid-labels','GET',null,a.headers);await f.order(a);const next=await f.call('/api/staff/paid-labels?revision='+encodeURIComponent(first.data.revision),'GET',null,a.headers);assert.equal(next.data.jobs.length,1);assert.notEqual(next.data.revision,first.data.revision)}finally{f.db.close()}});
test('PRINT payment makes the revision change without creating a kitchen job',async()=>{const f=currentFixture(),a=f.actor();try{const order=(await f.order(a)).data.order,first=(await f.call('/api/staff/paid-labels','GET',null,a.headers)).data;await f.call('/api/staff/orders/'+order.id+'/pay','POST',{version:order.version,method:'CASH',received:order.total},a.headers);const next=(await f.call('/api/staff/paid-labels?revision='+encodeURIComponent(first.revision),'GET',null,a.headers)).data;assert.deepEqual(next.jobs,[]);assert.notEqual(next.revision,first.revision);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM pos_kitchen_jobs').get().n,1)}finally{f.db.close()}});

test('APPEND retry with the same key adds items and kitchen delta exactly once',async()=>{const f=currentFixture(),a=f.actor();try{const order=(await f.order(a)).data.order,payload={version:order.version,items:[f.item()],idempotencyKey:crypto.randomUUID()},path='/api/staff/orders/'+order.id+'/append';assert.equal((await f.call(path,'POST',payload,a.headers)).status,200);assert.equal((await f.call(path,'POST',payload,a.headers)).status,200);const row=f.db.prepare('SELECT items_json,version FROM qr_orders WHERE id=?').get(order.id);assert.equal(JSON.parse(row.items_json).reduce((n,x)=>n+x.qty,0),2);assert.equal(row.version,2);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM pos_kitchen_jobs').get().n,2);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM pos_order_append_requests').get().n,1)}finally{f.db.close()}});
test('APPEND replay still succeeds after the parent has been paid',async()=>{const f=currentFixture(),a=f.actor();try{const order=(await f.order(a)).data.order,payload={version:order.version,items:[f.item()],idempotencyKey:crypto.randomUUID()},path='/api/staff/orders/'+order.id+'/append';const appended=(await f.call(path,'POST',payload,a.headers)).data.order;assert.equal((await f.call('/api/staff/orders/'+order.id+'/pay','POST',{version:appended.version,method:'CASH',received:appended.total},a.headers)).status,200);const replay=await f.call(path,'POST',payload,a.headers);assert.equal(replay.status,200);assert.equal(replay.data.order.paymentStatus,'PAID');assert.equal(f.db.prepare('SELECT COUNT(*) n FROM qr_orders').get().n,1)}finally{f.db.close()}});
test('APPEND reusing a key with changed items is rejected',async()=>{const f=currentFixture(),a=f.actor();try{const order=(await f.order(a)).data.order,payload={version:order.version,items:[f.item()],idempotencyKey:crypto.randomUUID()},path='/api/staff/orders/'+order.id+'/append';await f.call(path,'POST',payload,a.headers);const retry=await f.call(path,'POST',{...payload,items:[f.item(2)]},a.headers);assert.equal(retry.status,409);assert.equal(retry.data.code,'REQUEST_ID_REUSED')}finally{f.db.close()}});
test('APPEND compare-and-swap conflict rolls back the receipt and kitchen delta',async()=>{const f=currentFixture(),a=f.actor();try{const order=(await f.order(a)).data.order;f.DB.beforeBatch=()=>f.db.prepare('UPDATE qr_orders SET version=version+1 WHERE id=?').run(order.id);const response=await f.call('/api/staff/orders/'+order.id+'/append','POST',{version:order.version,items:[f.item()],idempotencyKey:crypto.randomUUID()},a.headers);assert.equal(response.status,409);assert.equal(response.data.code,'ORDER_CHANGED');assert.equal(f.db.prepare('SELECT COUNT(*) n FROM pos_order_append_requests').get().n,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM pos_kitchen_jobs').get().n,1);assert.equal(JSON.parse(f.db.prepare('SELECT items_json FROM qr_orders WHERE id=?').get(order.id).items_json).length,1)}finally{f.db.close()}});

function submitHarness(f,a,order){
 const state={cart:[f.item()],table:order.table,appendTarget:{id:order.id,code:order.code,table:order.table},idem:crypto.randomUUID(),orderNote:'',member:null,voucher:'',busy:false};const saved=new Map();let drop=false;
 const context={st:state,approve:()=>true,render(){},refresh:async()=>{},message(){},id:()=>crypto.randomUUID(),store:{set:(k,v)=>saved.set(k,v),del:k=>saved.delete(k)},$:()=>null,api:async(method,path,body)=>{const r=await f.call(path,method,body,a.headers);if(r.status>=400){const error=Error(r.data.message);error.status=r.status;error.code=r.data.code;throw error}if(drop&&method==='POST'){drop=false;throw Error('Lost response after commit')}return r.data}};
 const start=STAFF.indexOf(" if(action==='submit'){");const end=STAFF.indexOf("\n if(action==='lookup')",start);const code='(async()=>{const action="submit";'+STAFF.slice(start,end)+'})()';
 return {state,saved,dropNext(){drop=true},submit:()=>vm.runInNewContext(code,context)};
}
test('RECOVERY a lost response to supplementary creation reuses the same order',async()=>{const f=currentFixture(),a=f.actor();try{const order=(await f.order(a)).data.order;await f.call('/api/staff/orders/'+order.id+'/cancel','POST',{version:order.version,reason:'QA closed'},a.headers);const h=submitHarness(f,a,order);h.dropNext();await h.submit();assert.equal(h.state.cart.length,1);assert.equal(h.state.uncertain,true);assert.ok(h.saved.has('order-draft'));await h.submit();assert.equal(h.state.cart.length,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM qr_orders').get().n,2);assert.ok(!h.saved.has('order-draft'))}finally{f.db.close()}});
test('RECOVERY a committed append followed by payment never creates another order',async()=>{const f=currentFixture(),a=f.actor();try{const order=(await f.order(a)).data.order,h=submitHarness(f,a,order);h.dropNext();await h.submit();const appended=f.db.prepare('SELECT version,total FROM qr_orders WHERE id=?').get(order.id);await f.call('/api/staff/orders/'+order.id+'/pay','POST',{version:appended.version,method:'CASH',received:appended.total},a.headers);await h.submit();assert.equal(h.state.cart.length,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM qr_orders').get().n,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM pos_kitchen_jobs').get().n,2)}finally{f.db.close()}});

const schedulerSource=STAFF.slice(STAFF.indexOf('const scheduler={'),STAFF.indexOf("if(typeof window.setInterval==='function')window.setInterval(schedulerTick,1000);"));
function schedulerHarness(){
 let clock=0,serial=0;const timers=new Map(),counts={live:0,service:0,print:0,scanner:0};
 const context={st:{token:'token',syncStats:{realtime:0},realtimeState:'OFFLINE',selected:null},counter:true,native:null,document:{hidden:false},can:()=>true,location:{protocol:'https:',origin:'https://pos.test'},Date:{now:()=>clock},console,Math,setTimeout:(fn,ms)=>{const id=++serial;timers.set(id,{fn,ms});return id},clearTimeout:id=>timers.delete(id),setInterval:()=>++serial,clearInterval(){},syncLive:async()=>{counts.live++},pollService:async()=>{counts.service++},pollScanner:async()=>{counts.scanner++},pollAutoPrint:async()=>{counts.print++},watchOrders:async()=>{counts.announce=(counts.announce||0)+1},announceOn:()=>false,kitchenOnly:()=>false,liveFetchesOrders:()=>true};
 vm.createContext(context);vm.runInContext(schedulerSource+';globalThis.t={scheduler,runScheduled,taskDelay,taskBase,wakeSync,connectRealtime,closeRealtime,realtime};',context);
 return {context,counts,timers,t:context.t,time:value=>clock=value,flush:async()=>{for(let i=0;i<8;i++)await Promise.resolve()}};
}
test('SCHEDULER concurrent wake-ups never overlap and coalesce one trailing run',async()=>{const h=schedulerHarness();let resolve,calls=0;h.t.scheduler.live.fn=()=>{calls++;return new Promise(done=>resolve=done)};h.t.runScheduled('live',true);await h.flush();for(let i=0;i<50;i++)h.t.runScheduled('live',true);assert.equal(calls,1);resolve();await h.flush();assert.equal(calls,2);resolve();await h.flush();assert.equal(h.t.scheduler.live.running,false)});
test('SCHEDULER failed requests back off instead of being retriggered immediately',async()=>{const h=schedulerHarness();h.t.scheduler.live.fn=async()=>{throw Error('offline')};await h.t.runScheduled('live');assert.equal(h.t.scheduler.live.fail,1);assert.equal(h.t.scheduler.live.next,30000);h.time(1000);h.t.runScheduled('live');assert.equal(h.t.scheduler.live.fail,1)});
test('SCHEDULER hidden or logged-out clients do not issue requests',async()=>{const h=schedulerHarness();h.context.document.hidden=true;h.t.runScheduled('live',true);h.context.document.hidden=false;h.context.st.token=null;h.t.runScheduled('print',true);await h.flush();assert.equal(h.counts.live+h.counts.print,0)});
test('SCHEDULER realtime reduces safety polling; print pull relaxes to 10 s only while realtime is online, 3 s otherwise',()=>{const h=schedulerHarness();h.context.st.realtimeState='ONLINE';assert.equal(h.t.taskBase(h.t.scheduler.live),60000);assert.equal(h.t.taskBase(h.t.scheduler.service),60000);assert.equal(h.t.taskBase(h.t.scheduler.print),10000);h.context.st.realtimeState='OFFLINE';assert.equal(h.t.taskBase(h.t.scheduler.print),3000);assert.equal(h.t.taskBase(h.t.scheduler.live),15000)});
test('SCHEDULER fifty print events wake one print pull and no full order sync',async()=>{const h=schedulerHarness();for(let i=0;i<50;i++)h.t.wakeSync('print');assert.equal(h.timers.size,1);[...h.timers.values()][0].fn();await h.flush();assert.equal(h.counts.print,1);assert.equal(h.counts.live+h.counts.service,0)});
test('SCHEDULER a service alert only wakes its own reader',async()=>{const h=schedulerHarness();h.t.wakeSync('service');[...h.timers.values()][0].fn();await h.flush();assert.equal(h.counts.service,1);assert.equal(h.counts.live+h.counts.print,0)});
test('REALTIME explicit close ignores callbacks from an obsolete socket',()=>{const h=schedulerHarness();const sockets=[];h.context.WebSocket=class{constructor(){this.readyState=0;sockets.push(this)}close(){this.onclose?.()}};h.t.connectRealtime();assert.equal(sockets.length,1);h.t.closeRealtime();assert.equal(h.t.realtime.ws,null);assert.equal(h.timers.size,0)});
test('REALTIME write classification isolates print claims and display updates',()=>{assert.deepEqual(mutationScopes('/api/staff/jobs/abc/status'),['print']);assert.deepEqual(mutationScopes('/api/staff/display/abc'),[]);assert.deepEqual(mutationScopes('/api/staff/logout'),[]);assert.deepEqual(mutationScopes('/api/staff/service-requests/abc/ack'),['service'])});
test('REALTIME the packaged SUNMI app may connect from file:// whether its WebView says null or file://',async()=>{
 for(const Origin of ['null','file://']){
  const r=await worker.fetch(new Request('https://pos.test/api/realtime',{headers:{Upgrade:'websocket',Origin,'Sec-Fetch-Site':'cross-site'}}),{REALTIME:{}});
  assert.notEqual(r.status,403,Origin+' must reach the session check, not be rejected as cross-site');
 }
 for(const Origin of ['https://evil.test','file://evil','http://localhost']){
  const r=await worker.fetch(new Request('https://pos.test/api/realtime',{headers:{Upgrade:'websocket',Origin}}),{REALTIME:{}});
  assert.equal(r.status,403,Origin);
 }
});
test('REALTIME cross-origin and unconfigured upgrades fail without throwing',async()=>{let r=await worker.fetch(new Request('https://pos.test/api/realtime',{headers:{Upgrade:'websocket',Origin:'https://evil.test'}}),{REALTIME:{}});assert.equal(r.status,403);r=await worker.fetch(new Request('https://pos.test/api/realtime',{headers:{Upgrade:'websocket',Origin:'https://pos.test'}}),{REALTIME:{}});assert.equal(r.status,503)});
test('REALTIME expired sockets receive no invalidation and are closed',async()=>{const received=[],closed=[];const ws={deserializeAttachment:()=>({expiresAt:Date.now()-1}),send:x=>received.push(x),close:(code)=>closed.push(code)};const hub=new RealtimeHub({getWebSockets:()=>[ws]},{});await hub.fetch(new Request('https://realtime.internal/notify',{method:'POST',body:'{"scope":"orders"}'}));assert.equal(received.length,0);assert.deepEqual(closed,[1008])});
test('REALTIME a slow notifier does not delay a committed order response',async()=>{const f=currentFixture(),a=f.actor(),work=[];let resolve;try{f.env.REALTIME={idFromName:()=>1,get:()=>({fetch:()=>new Promise(done=>resolve=done)})};const r=await f.call('/api/staff/orders','POST',{table:'T01',items:[f.item()],idempotencyKey:crypto.randomUUID()},a.headers,{waitUntil:job=>work.push(job)});assert.equal(r.status,201);assert.equal(work.length,1);resolve(new Response('ok'));await work[0]}finally{f.db.close()}});
test('READINESS cold concurrent health requests share one probe',async()=>{let probes=0,resolve;const env={DB:{prepare(){return {bind(){return this},first(){probes++;return new Promise(done=>resolve=done)}}}},SESSION_SECRET:'readiness-test-012345678901234567890123',ORDERING_ENABLED:'true'};const requests=Array.from({length:20},()=>worker.fetch(new Request('https://pos.test/api/health'),env));assert.equal(probes,1);resolve({ok:1});const results=await Promise.all(requests);assert.ok(results.every(r=>r.status===200));assert.equal(probes,1)});
test('READINESS missing migration is negatively cached without extra probes',async()=>{let probes=0;const env={DB:{prepare(){return {bind(){return this},async first(){probes++;return null}}}},SESSION_SECRET:'readiness-test-012345678901234567890123',ORDERING_ENABLED:'true'};for(let i=0;i<10;i++){const r=await worker.fetch(new Request('https://pos.test/api/health'),env);assert.equal((await r.json()).acceptingOrders,false)}assert.equal(probes,1)});
test('SCHEDULER invalidations respect backoff after a failure',async()=>{const h=schedulerHarness();let calls=0;h.t.scheduler.live.fn=async()=>{calls++;throw Error('offline')};await h.t.runScheduled('live');for(let i=0;i<50;i++)h.t.runScheduled('live',true);await h.flush();assert.equal(calls,1)});
test('SYNC an unchanged screen makes one small read and no full order or menu reads',async()=>{
 const revisions={orders:'2',print:'2',catalog:'1',inventory:'1',staff:'1',reports:'1'},paths=[];
 const state={token:'token',screen:'orders',selected:null,busy:false,syncRevisions:{...revisions},syncStats:{orders:0}};
 const code=STAFF.slice(STAFF.indexOf('async function syncLive(){'),STAFF.indexOf('\nfunction renderLogin()'));
 await vm.runInNewContext('let liveSyncing=false;'+code+';syncLive()',{LIVE_SCREENS:['orders','qrorders','kitchen','new','inventory','dashboard','display','products','team','vouchers','shifts','customers','store'],announceOrders(){},st:state,document:{hidden:false,activeElement:null},can:()=>true,counter:false,api:async(method,path)=>{paths.push(path);return {revisions}},render(){},connection(){}});
 assert.deepEqual(paths,['/api/staff/sync-meta']);assert.equal(state.syncStats.orders,0);
});
test('API concurrent identical reads share one network request',async()=>{
 const start=STAFF.indexOf('const apiReads=new Map();'),end=STAFF.indexOf('\nfunction connection()',start);const code=STAFF.slice(start,end);
 let reads=0;const context={st:{token:'token',online:false},native:null,connection(){},AbortSignal,fetch:async()=>{reads++;return {status:200,text:async()=>JSON.stringify({ok:true})}}};
 await vm.runInNewContext(code+";Promise.all([api('GET','/api/staff/sync-meta'),api('GET','/api/staff/sync-meta')])",context);assert.equal(reads,1);
});
