import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {applyCurrentSchema} from './helpers/schema.mjs';
import worker from '../src/worker.js';

const STAFF=readFileSync(new URL('../public/staff/staff.js',import.meta.url),'utf8');
const STAFF_CSS=readFileSync(new URL('../public/staff/staff.css',import.meta.url),'utf8');
const QR=readFileSync(new URL('../public/assets/app.js',import.meta.url),'utf8');
const QR_CSS=readFileSync(new URL('../public/assets/app.css',import.meta.url),'utf8');
const MAIN=readFileSync(new URL('../android/app/src/main/java/vn/lotusai/pos/phattaiapp/MainActivity.java',import.meta.url),'utf8');
const SHIFT_UI=readFileSync(new URL('../public/counter/shift-ui.js',import.meta.url),'utf8');

function fixture(){
 const db=new DatabaseSync(':memory:');applyCurrentSchema(db);
 db.exec('UPDATE pos_product_inventory SET stock=100; UPDATE pos_ingredients SET stock=100000;');
 const DB={prepare(sql){let args=[];return {bind(...v){args=v;return this},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:r.changes}}},_run(){return db.prepare(sql).run(...args)}}},async batch(statements){db.exec('BEGIN');try{const out=statements.map(s=>s._run());db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}};
 const env={DB,ASSETS:{fetch:async()=>new Response('not found',{status:404})},ORDERING_ENABLED:'true',ALLOW_UNVERIFIED_MEMBER_VOUCHERS:'true',SESSION_SECRET:'phattai-test-secret-012345678901234567890123',POS_STAFF_PASSWORD:'phattai-test-password'};
 const call=async(path,method='GET',body=null,headers={})=>{const h={Origin:'https://pos-phattai.test',...headers};if(body!==null&&!('Content-Type' in h))h['Content-Type']='application/json';const r=await worker.fetch(new Request('https://pos-phattai.test'+path,{method,headers:h,body:body===null?undefined:(typeof body==='string'?body:JSON.stringify(body))}),env);const ct=r.headers.get('content-type')||'';return {status:r.status,data:ct.includes('json')?await r.json():await r.text(),headers:r.headers}};
 return {db,env,call};
}
const sha=x=>createHash('sha256').update(x).digest('hex');
async function owner(fx){const r=await fx.call('/api/staff/login','POST',{username:'huang',password:'phattai-test-password'});assert.equal(r.status,200);return {headers:{Authorization:'Bearer '+r.data.token},id:'OWNER',role:'OWNER'};}
function role(fx,roleName='CASHIER'){
 const id=crypto.randomUUID(),token=('tok_'+roleName.toLowerCase()+'_'+id.replaceAll('-','')).slice(0,70),username=(roleName.toLowerCase()+'_'+id.slice(0,8));const at=new Date().toISOString();
 fx.db.prepare('INSERT INTO pos_staff_users(id,username,display_name,role_id,password_salt,password_hash,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,username,roleName+' QA',roleName,'dummy','dummy',1,at,at);
 fx.db.prepare('INSERT INTO pos_staff_sessions(token_hash,expires_at,staff_id) VALUES(?,?,?)').run(sha(token),Date.now()+3600000,id);
 return {headers:{Authorization:'Bearer '+token},id,role:roleName,username};
}
async function qrOrder(fx,{table='T01',productId='101',qty=1,items=null,voucherCode='',memberId=null,idem=crypto.randomUUID().replaceAll('-','')}={}){
 return fx.call('/api/orders','POST',{table,idempotencyKey:'deep_'+idem,items:items||[{productId,qty,mods:{size:'中',spice:'中',note:''}}],voucherCode,memberId});
}
async function staffOrder(fx,a,{table='T01',items=null,voucherCode='',memberId=null,idem=crypto.randomUUID().replaceAll('-','')}={}){
 return fx.call('/api/staff/orders','POST',{table,idempotencyKey:'deepstaff_'+idem,items:items||[{productId:'101',qty:1,mods:{size:'中',spice:'中',note:''}}],voucherCode,memberId,note:''},a.headers);
}
async function detail(fx,a,id){return fx.call('/api/staff/orders/'+id,'GET',null,a.headers)}
async function payOrder(fx,a,id,version,method='CASH',received=999999){return fx.call('/api/staff/orders/'+id+'/pay','POST',{version,method,...(method==='CASH'?{received}:{})},a.headers)}
function dayPlus(n=1){const d=new Date();const s=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);const x=new Date(s+'T00:00:00Z');x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)}

// ROLE / PERMISSION CROSS-CHECKS
for(const [name,expected] of Object.entries({OWNER:['ORDER_VIEW','ORDER_EDIT','PAYMENT_CONFIRM','PRINT_KITCHEN','INVENTORY_VIEW','INVENTORY_MANAGE','REFUND_VIEW','REFUND_CREATE','STAFF_MANAGE','CUSTOMER_MANAGE','ROLE_MANAGE','SHIFT_MANAGE','ATTENDANCE_VIEW','CATALOG_MANAGE','VOUCHER_MANAGE'],MANAGER:['ORDER_VIEW','ORDER_EDIT','PAYMENT_CONFIRM','PRINT_KITCHEN','INVENTORY_VIEW','INVENTORY_MANAGE','REFUND_VIEW','REFUND_CREATE','SHIFT_MANAGE','ATTENDANCE_VIEW','CUSTOMER_MANAGE'],CASHIER:['ORDER_VIEW','ORDER_EDIT','PAYMENT_CONFIRM','PRINT_KITCHEN','INVENTORY_VIEW','REFUND_VIEW'],KITCHEN:['ORDER_VIEW','PRINT_KITCHEN']})){
 test(`ROLE ${name} exposes expected permissions`,async()=>{const fx=fixture(),a=name==='OWNER'?await owner(fx):role(fx,name);const me=await fx.call('/api/staff/me','GET',null,a.headers);for(const p of expected)assert.ok(me.data.staff.permissions.includes(p),`${name} missing ${p}`);fx.db.close()});
}
test('ROLE manager product-management expectation from business spec',async()=>{const fx=fixture(),m=role(fx,'MANAGER');const r=await fx.call('/api/staff/products','GET',null,m.headers);assert.equal(r.status,200,'Manager should manage menu/products per PHAT TAI role design');fx.db.close()});
test('ROLE manager cannot administer vouchers',async()=>{const fx=fixture(),m=role(fx,'MANAGER');const r=await fx.call('/api/staff/vouchers','GET',null,m.headers);assert.equal(r.status,403);fx.db.close()});
test('ROLE cashier cannot modify inventory',async()=>{const fx=fixture(),c=role(fx,'CASHIER');const r=await fx.call('/api/staff/inventory/adjust','POST',{target:'PRODUCT',id:'101',kind:'RECEIPT',quantity:1,reference:'QA',idempotencyKey:'cashier_inventory_12345'},c.headers);assert.equal(r.status,403);fx.db.close()});
test('ROLE kitchen cannot edit order',async()=>{const fx=fixture(),o=await qrOrder(fx),k=role(fx,'KITCHEN'),d=await detail(fx,k,o.data.order.id);const r=await fx.call('/api/staff/orders/'+o.data.order.id+'/append','POST',{version:d.data.order.version,items:[{productId:'110',qty:1,mods:{size:'中',spice:'中',note:''}}]},k.headers);assert.equal(r.status,403);fx.db.close()});
test('ROLE owner report endpoint allowed, manager denied',async()=>{const fx=fixture(),o=await owner(fx),m=role(fx,'MANAGER'),day=dayPlus(0);assert.equal((await fx.call('/api/staff/reports/daily?date='+day,'GET',null,o.headers)).status,200);assert.equal((await fx.call('/api/staff/reports/daily?date='+day,'GET',null,m.headers)).status,403);fx.db.close()});

// PRINTING / ORDER EVENT MATRIX
test('PRINT QR order creates one kitchen NEW job while unpaid',async()=>{const fx=fixture(),o=await qrOrder(fx);const jobs=fx.db.prepare('select kind,status from pos_kitchen_jobs where order_id=?').all(o.data.order.id);assert.equal(jobs.length,1);assert.equal(jobs[0].kind,'NEW');assert.equal(jobs[0].status,'PENDING');fx.db.close()});
test('PRINT staff order creates one kitchen NEW job while unpaid',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),o=await staffOrder(fx,c);assert.equal(fx.db.prepare('select count(*) n from pos_kitchen_jobs where order_id=?').get(o.data.order.id).n,1);fx.db.close()});
test('PRINT append creates exactly one ADD delta job',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),o=await qrOrder(fx),d=await detail(fx,c,o.data.order.id);await fx.call('/api/staff/orders/'+o.data.order.id+'/append','POST',{version:d.data.order.version,items:[{productId:'110',qty:1,mods:{size:'中',spice:'中',note:''}}]},c.headers);const jobs=fx.db.prepare('select kind from pos_kitchen_jobs where order_id=? order by revision').all(o.data.order.id);assert.deepEqual(jobs.map(x=>x.kind),['NEW','ADD']);fx.db.close()});
test('PRINT cancel one unit creates one CANCEL delta job',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),o=await qrOrder(fx,{qty:2}),d=await detail(fx,c,o.data.order.id);await fx.call('/api/staff/orders/'+o.data.order.id+'/cancel-unit','POST',{version:d.data.order.version,index:0,reason:'qa'},c.headers);const jobs=fx.db.prepare('select kind from pos_kitchen_jobs where order_id=? order by revision').all(o.data.order.id);assert.deepEqual(jobs.map(x=>x.kind),['NEW','CANCEL']);fx.db.close()});
test('PRINT full order cancellation creates CANCEL job visible to automatic kitchen queue',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),k=role(fx,'KITCHEN'),o=await qrOrder(fx),d=await detail(fx,c,o.data.order.id);await fx.call('/api/staff/orders/'+o.data.order.id+'/cancel','POST',{version:d.data.order.version,reason:'qa cancel'},c.headers);const job=fx.db.prepare("select id,kind,status from pos_kitchen_jobs where order_id=? order by revision desc limit 1").get(o.data.order.id);assert.equal(job.kind,'CANCEL');const q=await fx.call('/api/staff/paid-labels','GET',null,k.headers);assert.ok(q.data.jobs.some(x=>x.id===job.id),'cancel ticket must be auto-printable');fx.db.close()});
test('PRINT last-unit cancellation creates CANCEL job visible to queue',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),k=role(fx,'KITCHEN'),o=await qrOrder(fx,{qty:1}),d=await detail(fx,c,o.data.order.id);await fx.call('/api/staff/orders/'+o.data.order.id+'/cancel-unit','POST',{version:d.data.order.version,index:0,reason:'qa last'},c.headers);const job=fx.db.prepare("select id,kind from pos_kitchen_jobs where order_id=? order by revision desc limit 1").get(o.data.order.id);assert.equal(job.kind,'CANCEL');const q=await fx.call('/api/staff/paid-labels','GET',null,k.headers);assert.ok(q.data.jobs.some(x=>x.id===job.id));fx.db.close()});
test('PRINT split does not create kitchen job',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),o=await qrOrder(fx,{qty:2}),d=await detail(fx,c,o.data.order.id);await fx.call('/api/staff/orders/'+o.data.order.id+'/split','POST',{version:d.data.order.version,parts:[[{index:0,qty:1}],[{index:0,qty:1}]]},c.headers);assert.equal(fx.db.prepare('select count(*) n from pos_kitchen_jobs where order_id=?').get(o.data.order.id).n,1);fx.db.close()});
test('PRINT merge bills does not create kitchen job',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),o=await qrOrder(fx,{qty:3}),d=await detail(fx,c,o.data.order.id);const s=await fx.call('/api/staff/orders/'+o.data.order.id+'/split','POST',{version:d.data.order.version,parts:[[{index:0,qty:1}],[{index:0,qty:1}],[{index:0,qty:1}]]},c.headers);const r=await fx.call('/api/staff/orders/'+o.data.order.id+'/merge-bills','POST',{version:s.data.order.version,billIds:[s.data.bills[0].id,s.data.bills[1].id]},c.headers);assert.equal(r.status,200);assert.equal(fx.db.prepare('select count(*) n from pos_kitchen_jobs where order_id=?').get(o.data.order.id).n,1);fx.db.close()});
test('PRINT CASH payment creates no additional kitchen job',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),o=await qrOrder(fx),d=await detail(fx,c,o.data.order.id);await payOrder(fx,c,o.data.order.id,d.data.order.version,'CASH',d.data.order.total);assert.equal(fx.db.prepare('select count(*) n from pos_kitchen_jobs where order_id=?').get(o.data.order.id).n,1);fx.db.close()});
test('PRINT BANK payment creates no additional kitchen job',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),o=await qrOrder(fx),d=await detail(fx,c,o.data.order.id);await payOrder(fx,c,o.data.order.id,d.data.order.version,'BANK');assert.equal(fx.db.prepare('select count(*) n from pos_kitchen_jobs where order_id=?').get(o.data.order.id).n,1);fx.db.close()});
test('PRINT paid order cannot reclaim old kitchen job',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),k=role(fx,'KITCHEN'),o=await qrOrder(fx),d=await detail(fx,c,o.data.order.id);const job=fx.db.prepare('select id from pos_kitchen_jobs where order_id=?').get(o.data.order.id);await payOrder(fx,c,o.data.order.id,d.data.order.version,'BANK');const r=await fx.call('/api/staff/jobs/'+encodeURIComponent(job.id)+'/claim','POST',{},k.headers);assert.equal(r.status,409);fx.db.close()});
test('PRINT frontend payment callback calls receipt, not kitchen',()=>{const paymentBlock=STAFF.slice(STAFF.indexOf('if(b.dataset.pay)'),STAFF.indexOf("if(b.dataset.receipt)"));assert.match(paymentBlock,/printReceipt\(r\.order,paidBill\)/);assert.doesNotMatch(paymentBlock,/printKitchen|printJob|nativeKitchenAuto/)});
test('PRINT native receipt and kitchen routes are separate',()=>{assert.match(MAIN,/printReceipt\(String id,String payload\)[\s\S]{0,180}submitPrint\(id,"RECEIPT",payload\)/);assert.match(MAIN,/printKitchen\(String id,String payload\)[\s\S]{0,180}kitchen\.submit\(id,payload\)/)});

// SPLIT / BILL CONSISTENCY
test('SPLIT three bills preserve total',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),o=await qrOrder(fx,{qty:3}),d=await detail(fx,c,o.data.order.id);const s=await fx.call('/api/staff/orders/'+o.data.order.id+'/split','POST',{version:d.data.order.version,parts:[[{index:0,qty:1}],[{index:0,qty:1}],[{index:0,qty:1}]]},c.headers);assert.equal(s.status,200);assert.equal(s.data.bills.length,3);assert.equal(s.data.bills.reduce((x,b)=>x+b.total,0),s.data.order.total);fx.db.close()});
test('SPLIT partial payment leaves parent SPLIT/UNPAID',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),o=await qrOrder(fx,{qty:2}),d=await detail(fx,c,o.data.order.id);const s=await fx.call('/api/staff/orders/'+o.data.order.id+'/split','POST',{version:d.data.order.version,parts:[[{index:0,qty:1}],[{index:0,qty:1}]]},c.headers);const b=s.data.bills[0];const p=await fx.call('/api/staff/bills/'+encodeURIComponent(b.id)+'/pay','POST',{method:'CASH',received:b.total},c.headers);assert.equal(p.data.order.status,'SPLIT');assert.equal(p.data.order.paymentStatus,'UNPAID');fx.db.close()});
test('SPLIT final bill payment closes parent order',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),o=await qrOrder(fx,{qty:2}),d=await detail(fx,c,o.data.order.id);let s=await fx.call('/api/staff/orders/'+o.data.order.id+'/split','POST',{version:d.data.order.version,parts:[[{index:0,qty:1}],[{index:0,qty:1}]]},c.headers);for(const b of s.data.bills){s=await fx.call('/api/staff/bills/'+encodeURIComponent(b.id)+'/pay','POST',{method:'CASH',received:b.total},c.headers)}assert.equal(s.data.order.status,'PAID');assert.equal(s.data.order.paymentStatus,'PAID');fx.db.close()});
test('SPLIT cannot merge a paid bill with unpaid bill',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),o=await qrOrder(fx,{qty:3}),d=await detail(fx,c,o.data.order.id);let s=await fx.call('/api/staff/orders/'+o.data.order.id+'/split','POST',{version:d.data.order.version,parts:[[{index:0,qty:1}],[{index:0,qty:1}],[{index:0,qty:1}]]},c.headers);await fx.call('/api/staff/bills/'+encodeURIComponent(s.data.bills[0].id)+'/pay','POST',{method:'BANK'},c.headers);const current=await detail(fx,c,o.data.order.id);const r=await fx.call('/api/staff/orders/'+o.data.order.id+'/merge-bills','POST',{version:current.data.order.version,billIds:[current.data.bills[0].id,current.data.bills[1].id]},c.headers);assert.equal(r.status,409);fx.db.close()});
test('SPLIT each bill has distinct bank transfer content',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),o=await qrOrder(fx,{qty:2}),d=await detail(fx,c,o.data.order.id);const s=await fx.call('/api/staff/orders/'+o.data.order.id+'/split','POST',{version:d.data.order.version,parts:[[{index:0,qty:1}],[{index:0,qty:1}]]},c.headers);assert.notEqual(s.data.bills[0].bankPayment.content,s.data.bills[1].bankPayment.content);assert.match(s.data.bills[0].bankPayment.content,/B1$/);assert.match(s.data.bills[1].bankPayment.content,/B2$/);fx.db.close()});

// INVENTORY INDEPENDENCE
test('INV order creation does not change ledger stock',async()=>{const fx=fixture(),before=fx.db.prepare("select stock from pos_product_inventory where product_id='101'").get().stock;await qrOrder(fx,{qty:2});const after=fx.db.prepare("select stock from pos_product_inventory where product_id='101'").get().stock;assert.equal(after,before);fx.db.close()});
test('INV order creation decreases estimate only',async()=>{const fx=fixture(),before=fx.db.prepare("select estimated_stock from pos_inventory_estimates where target='PRODUCT' and ref_id='101'").get().estimated_stock;await qrOrder(fx,{qty:2});const after=fx.db.prepare("select estimated_stock from pos_inventory_estimates where target='PRODUCT' and ref_id='101'").get().estimated_stock;assert.equal(after,before-2);fx.db.close()});
test('INV append decreases estimate without touching ledger stock',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),o=await qrOrder(fx),before=fx.db.prepare("select estimated_stock from pos_inventory_estimates where target='PRODUCT' and ref_id='110'").get().estimated_stock,d=await detail(fx,c,o.data.order.id);await fx.call('/api/staff/orders/'+o.data.order.id+'/append','POST',{version:d.data.order.version,items:[{productId:'110',qty:2,mods:{size:'中',spice:'中',note:''}}]},c.headers);assert.equal(fx.db.prepare("select estimated_stock from pos_inventory_estimates where target='PRODUCT' and ref_id='110'").get().estimated_stock,before-2);assert.equal(fx.db.prepare("select stock from pos_product_inventory where product_id='110'").get().stock,100);fx.db.close()});
test('INV cancel unit restores estimate',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),before=fx.db.prepare("select estimated_stock from pos_inventory_estimates where target='PRODUCT' and ref_id='101'").get().estimated_stock,o=await qrOrder(fx,{qty:2}),d=await detail(fx,c,o.data.order.id);await fx.call('/api/staff/orders/'+o.data.order.id+'/cancel-unit','POST',{version:d.data.order.version,index:0,reason:'qa'},c.headers);const after=fx.db.prepare("select estimated_stock from pos_inventory_estimates where target='PRODUCT' and ref_id='101'").get().estimated_stock;assert.equal(after,before-1);fx.db.close()});
test('INV full cancel restores estimate completely',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),before=fx.db.prepare("select estimated_stock from pos_inventory_estimates where target='PRODUCT' and ref_id='101'").get().estimated_stock,o=await qrOrder(fx,{qty:2}),d=await detail(fx,c,o.data.order.id);await fx.call('/api/staff/orders/'+o.data.order.id+'/cancel','POST',{version:d.data.order.version,reason:'qa'},c.headers);assert.equal(fx.db.prepare("select estimated_stock from pos_inventory_estimates where target='PRODUCT' and ref_id='101'").get().estimated_stock,before);fx.db.close()});
test('INV manual receipt changes ledger and estimate but no order/kitchen records',async()=>{const fx=fixture(),m=role(fx,'MANAGER'),ob=fx.db.prepare('select count(*) n from qr_orders').get().n,jb=fx.db.prepare('select count(*) n from pos_kitchen_jobs').get().n;const before=fx.db.prepare("select stock from pos_product_inventory where product_id='101'").get().stock;const r=await fx.call('/api/staff/inventory/adjust','POST',{target:'PRODUCT',id:'101',kind:'RECEIPT',quantity:5,reference:'QA receipt',idempotencyKey:'manager_inventory_12345'},m.headers);assert.equal(r.status,200);assert.equal(fx.db.prepare("select stock from pos_product_inventory where product_id='101'").get().stock,before+5);assert.equal(fx.db.prepare('select count(*) n from qr_orders').get().n,ob);assert.equal(fx.db.prepare('select count(*) n from pos_kitchen_jobs').get().n,jb);fx.db.close()});
test('INV estimated stock may go negative without blocking sales',async()=>{const fx=fixture();fx.db.prepare("update pos_inventory_estimates set estimated_stock=-100 where target='PRODUCT' and ref_id='101'").run();const catalog=await fx.call('/api/catalog');assert.equal(catalog.data.catalog.products.find(x=>x.id==='101').available,true);const o=await qrOrder(fx);assert.equal(o.status,201);fx.db.close()});

// VOUCHER LIFECYCLE
async function makeVoucher(fx,a,{code='QA20',kind='PERCENT',value=20,minSpend=0,maxDiscount=0,memberOnly=false,maxUses=0,perMemberLimit=0}={}){return fx.call('/api/staff/vouchers','POST',{code,titleVi:'QA ưu đãi',titleZh:'QA 优惠',kind,value,minSpend,maxDiscount,memberOnly,active:true,listed:true,startsAt:new Date(Date.now()-3600000).toISOString(),endsAt:new Date(Date.now()+86400000).toISOString(),maxUses,perMemberLimit},a.headers)}
test('VOUCHER owner creates and public listing exposes listed voucher',async()=>{const fx=fixture(),o=await owner(fx);await makeVoucher(fx,o,{code:'PUB20'});const r=await fx.call('/api/vouchers');assert.ok(r.data.vouchers.some(v=>v.code==='PUB20'));fx.db.close()});
test('VOUCHER applies expected percent discount',async()=>{const fx=fixture(),o=await owner(fx);await makeVoucher(fx,o,{code:'PCT20'});const r=await fx.call('/api/vouchers/validate','POST',{table:'T01',items:[{productId:'110',qty:1,mods:{size:'中',spice:'中',note:''}}],voucherCode:'PCT20'});assert.equal(r.status,200);assert.equal(r.data.discount,16000);fx.db.close()});
test('VOUCHER min spend rejects low cart',async()=>{const fx=fixture(),o=await owner(fx);await makeVoucher(fx,o,{code:'MIN200',kind:'FIXED',value:10000,minSpend:200000});const r=await fx.call('/api/vouchers/validate','POST',{table:'T01',items:[{productId:'110',qty:1,mods:{size:'中',spice:'中',note:''}}],voucherCode:'MIN200'});assert.equal(r.status,400);assert.equal(r.data.code,'VOUCHER_MIN');fx.db.close()});
test('VOUCHER reservation held on order then redeemed on payment',async()=>{const fx=fixture(),own=await owner(fx),c=role(fx,'CASHIER');await makeVoucher(fx,own,{code:'HOLD20'});const o=await qrOrder(fx,{voucherCode:'HOLD20'});let row=fx.db.prepare("select status from voucher_reservations where order_id=?").get(o.data.order.id);assert.equal(row.status,'HELD');const d=await detail(fx,c,o.data.order.id);await payOrder(fx,c,o.data.order.id,d.data.order.version,'BANK');row=fx.db.prepare("select status from voucher_reservations where order_id=?").get(o.data.order.id);assert.equal(row.status,'REDEEMED');fx.db.close()});
test('VOUCHER reservation released on full cancel',async()=>{const fx=fixture(),own=await owner(fx),c=role(fx,'CASHIER');await makeVoucher(fx,own,{code:'REL20'});const o=await qrOrder(fx,{voucherCode:'REL20'}),d=await detail(fx,c,o.data.order.id);await fx.call('/api/staff/orders/'+o.data.order.id+'/cancel','POST',{version:d.data.order.version,reason:'qa'},c.headers);assert.equal(fx.db.prepare("select status from voucher_reservations where order_id=?").get(o.data.order.id).status,'RELEASED');fx.db.close()});
test('VOUCHER split payment redeems only after final bill',async()=>{const fx=fixture(),own=await owner(fx),c=role(fx,'CASHIER');await makeVoucher(fx,own,{code:'SPL20'});const o=await qrOrder(fx,{qty:2,voucherCode:'SPL20'}),d=await detail(fx,c,o.data.order.id);let s=await fx.call('/api/staff/orders/'+o.data.order.id+'/split','POST',{version:d.data.order.version,parts:[[{index:0,qty:1}],[{index:0,qty:1}]]},c.headers);await fx.call('/api/staff/bills/'+encodeURIComponent(s.data.bills[0].id)+'/pay','POST',{method:'BANK'},c.headers);assert.equal(fx.db.prepare("select status from voucher_reservations where order_id=?").get(o.data.order.id).status,'HELD');await fx.call('/api/staff/bills/'+encodeURIComponent(s.data.bills[1].id)+'/pay','POST',{method:'BANK'},c.headers);assert.equal(fx.db.prepare("select status from voucher_reservations where order_id=?").get(o.data.order.id).status,'REDEEMED');fx.db.close()});
test('VOUCHER frozen terms survive campaign edit on append',async()=>{const fx=fixture(),own=await owner(fx),c=role(fx,'CASHIER');const created=await makeVoucher(fx,own,{code:'FREEZE',kind:'PERCENT',value:20});const o=await qrOrder(fx,{voucherCode:'FREEZE'});const voucher=fx.db.prepare("select * from vouchers where code='FREEZE'").get();await fx.call('/api/staff/vouchers/'+created.data.id,'PATCH',{code:'FREEZE',titleVi:'new',titleZh:'new',kind:'PERCENT',value:5,minSpend:0,maxDiscount:0,memberOnly:false,active:true,listed:true,startsAt:voucher.starts_at,endsAt:voucher.ends_at,maxUses:0,perMemberLimit:0},own.headers);const d=await detail(fx,c,o.data.order.id);const r=await fx.call('/api/staff/orders/'+o.data.order.id+'/append','POST',{version:d.data.order.version,items:[{productId:'110',qty:1,mods:{size:'中',spice:'中',note:''}}]},c.headers);assert.equal(r.data.order.discount,Math.floor(r.data.order.subtotal*.20));fx.db.close()});

// SHIFT / ATTENDANCE / OT / SWAP
async function makeFutureSchedule(fx,manager,staffId,{date=dayPlus(2),start='08:00',end='12:00'}={}){return fx.call('/api/staff/schedules','POST',{staffId,workDate:date,startTime:start,endTime:end,note:'QA'},manager.headers)}
test('SHIFT manager can create future schedule',async()=>{const fx=fixture(),m=role(fx,'MANAGER'),c=role(fx,'CASHIER');const r=await makeFutureSchedule(fx,m,c.id);assert.equal(r.status,201);fx.db.close()});
test('SHIFT cashier cannot create schedule',async()=>{const fx=fixture(),c=role(fx,'CASHIER');const r=await fx.call('/api/staff/schedules','POST',{staffId:c.id,workDate:dayPlus(2),startTime:'08:00',endTime:'12:00',note:''},c.headers);assert.equal(r.status,403);fx.db.close()});
test('SHIFT overlapping schedule is rejected',async()=>{const fx=fixture(),m=role(fx,'MANAGER'),c=role(fx,'CASHIER'),date=dayPlus(2);assert.equal((await makeFutureSchedule(fx,m,c.id,{date,start:'08:00',end:'12:00'})).status,201);const r=await makeFutureSchedule(fx,m,c.id,{date,start:'11:00',end:'15:00'});assert.equal(r.status,409);fx.db.close()});
test('SHIFT adjacent non-overlap is accepted',async()=>{const fx=fixture(),m=role(fx,'MANAGER'),c=role(fx,'CASHIER'),date=dayPlus(2);await makeFutureSchedule(fx,m,c.id,{date,start:'08:00',end:'12:00'});const r=await makeFutureSchedule(fx,m,c.id,{date,start:'12:00',end:'16:00'});assert.equal(r.status,201);fx.db.close()});
test('SHIFT cashier sees only own schedule',async()=>{const fx=fixture(),m=role(fx,'MANAGER'),c1=role(fx,'CASHIER'),c2=role(fx,'CASHIER'),date=dayPlus(2);await makeFutureSchedule(fx,m,c1.id,{date});await makeFutureSchedule(fx,m,c2.id,{date,start:'13:00',end:'17:00'});const r=await fx.call('/api/staff/schedules?from='+date,'GET',null,c1.headers);assert.equal(r.data.schedules.length,1);assert.equal(r.data.schedules[0].staff_id,c1.id);fx.db.close()});
test('SHIFT manager sees all schedules',async()=>{const fx=fixture(),m=role(fx,'MANAGER'),c1=role(fx,'CASHIER'),c2=role(fx,'CASHIER'),date=dayPlus(2);await makeFutureSchedule(fx,m,c1.id,{date});await makeFutureSchedule(fx,m,c2.id,{date,start:'13:00',end:'17:00'});const r=await fx.call('/api/staff/schedules?from='+date,'GET',null,m.headers);assert.equal(r.data.schedules.length,2);fx.db.close()});
test('ATTENDANCE cashier clock-in then clock-out succeeds',async()=>{const fx=fixture(),c=role(fx,'CASHIER');assert.equal((await fx.call('/api/staff/attendance/in','POST',{note:'QA'},c.headers)).status,201);assert.equal((await fx.call('/api/staff/attendance/out','POST',{},c.headers)).status,200);fx.db.close()});
test('ATTENDANCE double clock-in conflicts, not duplicate',async()=>{const fx=fixture(),c=role(fx,'CASHIER');await fx.call('/api/staff/attendance/in','POST',{},c.headers);const r=await fx.call('/api/staff/attendance/in','POST',{},c.headers);assert.notEqual(r.status,201);fx.db.close()});
test('ATTENDANCE manager can see cashier attendance',async()=>{const fx=fixture(),m=role(fx,'MANAGER'),c=role(fx,'CASHIER');await fx.call('/api/staff/attendance/in','POST',{},c.headers);const day=dayPlus(0);const r=await fx.call('/api/staff/attendance?from='+day,'GET',null,m.headers);assert.ok(r.data.attendance.some(x=>x.staff_id===c.id));fx.db.close()});
test('OT cashier can request own overtime',async()=>{const fx=fixture(),c=role(fx,'CASHIER');const r=await fx.call('/api/staff/shift-ops/ot','POST',{requestKey:crypto.randomUUID(),workDate:dayPlus(2),startTime:'18:00',endTime:'20:00',reason:'QA overtime'},c.headers);assert.equal(r.status,201);fx.db.close()});
test('OT manager can request overtime for cashier',async()=>{const fx=fixture(),m=role(fx,'MANAGER'),c=role(fx,'CASHIER');const r=await fx.call('/api/staff/shift-ops/ot','POST',{requestKey:crypto.randomUUID(),staffId:c.id,workDate:dayPlus(2),startTime:'18:00',endTime:'20:00',reason:'QA overtime'},m.headers);assert.equal(r.status,201);fx.db.close()});
test('SHIFT task manager assigns and cashier completes',async()=>{const fx=fixture(),m=role(fx,'MANAGER'),c=role(fx,'CASHIER'),date=dayPlus(1);let r=await fx.call('/api/staff/shift-ops/task','POST',{requestKey:crypto.randomUUID(),workDate:date,titleVi:'Đóng cửa',titleZh:'关店',phase:'CLOSE',assigneeId:c.id,dueTime:'21:00',priority:'NORMAL'},m.headers);assert.equal(r.status,201);const row=fx.db.prepare("select * from pos_shift_tasks where assignee_id=? order by created_at desc limit 1").get(c.id);r=await fx.call('/api/staff/shift-ops/task/'+row.id+'/status','POST',{status:'DONE',version:row.version},c.headers);assert.equal(r.status,200);fx.db.close()});
test('SHIFT swap requires recipient acceptance before manager approval',async()=>{const fx=fixture(),m=role(fx,'MANAGER'),c1=role(fx,'CASHIER'),c2=role(fx,'CASHIER'),date=dayPlus(3);const sch=await makeFutureSchedule(fx,m,c1.id,{date});let r=await fx.call('/api/staff/shift-ops/swap','POST',{requestKey:crypto.randomUUID(),scheduleId:sch.data.id,toStaffId:c2.id,reason:'QA swap'},c1.headers);assert.equal(r.status,201);let row=fx.db.prepare('select * from pos_swap_requests order by created_at desc limit 1').get();r=await fx.call('/api/staff/shift-ops/swap/'+row.id+'/status','POST',{status:'APPROVED',version:row.version,note:''},m.headers);assert.equal(r.status,403);r=await fx.call('/api/staff/shift-ops/swap/'+row.id+'/status','POST',{status:'ACCEPTED',version:row.version},c2.headers);assert.equal(r.status,200);row=fx.db.prepare('select * from pos_swap_requests where id=?').get(row.id);r=await fx.call('/api/staff/shift-ops/swap/'+row.id+'/status','POST',{status:'APPROVED',version:row.version,note:'ok'},m.headers);assert.equal(r.status,200);fx.db.close()});

// DISPLAY
test('DISPLAY cashier with ORDER_EDIT can create pairing',async()=>{const fx=fixture(),c=role(fx,'CASHIER');const r=await fx.call('/api/staff/display','POST',{},c.headers);assert.equal(r.status,201);assert.ok(r.data.token);fx.db.close()});
test('DISPLAY kitchen role cannot create pairing',async()=>{const fx=fixture(),k=role(fx,'KITCHEN');const r=await fx.call('/api/staff/display','POST',{},k.headers);assert.equal(r.status,403);fx.db.close()});
test('DISPLAY draft snapshot mirrors cart total',async()=>{const fx=fixture(),c=role(fx,'CASHIER');const pair=await fx.call('/api/staff/display','POST',{},c.headers);const put=await fx.call('/api/staff/display/'+pair.data.id,'PUT',{revision:1,table:'T01',items:[{productId:'110',qty:2,mods:{size:'中',spice:'中',note:''}}]},c.headers);assert.equal(put.status,200);assert.equal(put.data.snapshot.total,160000);const pub=await fx.call('/api/display/'+pair.data.id,'GET',null,{'X-Display-Token':pair.data.token});assert.equal(pub.data.snapshot.total,160000);fx.db.close()});
test('DISPLAY stale revision does not overwrite newer snapshot',async()=>{const fx=fixture(),c=role(fx,'CASHIER');const pair=await fx.call('/api/staff/display','POST',{},c.headers);await fx.call('/api/staff/display/'+pair.data.id,'PUT',{revision:2,table:'T02',items:[]},c.headers);const stale=await fx.call('/api/staff/display/'+pair.data.id,'PUT',{revision:1,table:'T01',items:[]},c.headers);assert.equal(stale.data.stale,true);const pub=await fx.call('/api/display/'+pair.data.id,'GET',null,{'X-Display-Token':pair.data.token});assert.equal(pub.data.snapshot.table,'T02');fx.db.close()});
test('DISPLAY revoke invalidates public token',async()=>{const fx=fixture(),c=role(fx,'CASHIER');const pair=await fx.call('/api/staff/display','POST',{},c.headers);await fx.call('/api/staff/display/'+pair.data.id,'DELETE',{},c.headers);const pub=await fx.call('/api/display/'+pair.data.id,'GET',null,{'X-Display-Token':pair.data.token});assert.equal(pub.status,403);fx.db.close()});
test('DISPLAY selected paid order hides bank QR',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),o=await qrOrder(fx),d=await detail(fx,c,o.data.order.id);await payOrder(fx,c,o.data.order.id,d.data.order.version,'BANK');const pair=await fx.call('/api/staff/display','POST',{},c.headers);const put=await fx.call('/api/staff/display/'+pair.data.id,'PUT',{revision:1,orderId:o.data.order.id},c.headers);assert.equal(put.data.snapshot.paymentStatus,'PAID');assert.equal(put.data.snapshot.bankPayment,null);fx.db.close()});

// UI / STUCK GUARDS / FORMAT
test('UI mutation always clears busy flag in finally',()=>assert.match(STAFF,/async function mutation[\s\S]*finally\{st\.busy=false;render\(\)\}/));
test('UI live sync avoids rerender while active form is focused',()=>assert.match(STAFF,/!document\.activeElement\?\.closest\?\.\('form'\)/));
test('UI new-order screen preserves cart while background sync runs',()=>assert.match(STAFF,/if\(updated&&screen==='new'\)\{const list=\$\('#pos-menu-stock'\)/));
test('UI payment success assigns fresh detail response before final render',()=>assert.match(STAFF,/st\.detail=r/));
test('UI refund form function exists and is gated to paid transactions',()=>{assert.match(STAFF,/function refundForm\(/);assert.match(STAFF,/o\.paymentStatus==='PAID'\?refundForm/)});
test('UI owner handheld nav groups admin under one parent',()=>{assert.match(STAFF,/\['owner','Quản trị chủ tiệm \/ 店主管理'/);assert.doesNotMatch(STAFF,/\.\.\.\(owner\?\[\['products'/)});
test('UI staff Chinese equal-size helper exists',()=>assert.match(STAFF_CSS,/\.zh-equal\{font-size:1em!important/));
test('UI QR Chinese product name font equals Vietnamese font',()=>assert.match(QR_CSS,/\.product \.cn\{font-size:13px/));
test('UI QR modifier sheet scrolls rather than freezing viewport',()=>{assert.match(QR_CSS,/\.sheet-body\{[^}]*overflow-y:auto/);assert.match(QR_CSS,/max-height:min\(94dvh,900px\)/)});
test('UI customer QR cannot directly confirm payment',()=>assert.doesNotMatch(QR,/payment-reported|confirm-payment|data-action="pay"/));
test('UI staff print polling is guarded against concurrent overlap',()=>assert.match(STAFF,/if\(autoPrintPolling\|\|/));
test('UI order live sync is guarded against concurrent overlap',()=>assert.match(STAFF,/if\(liveSyncing\|\|/));
test('UI shift component has bilingual labels',()=>{assert.match(SHIFT_UI,/周|班|交接|加班/)});

test('PRINT cancelled order queue contains CANCEL only, not stale NEW',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),k=role(fx,'KITCHEN'),o=await qrOrder(fx),d=await detail(fx,c,o.data.order.id);await fx.call('/api/staff/orders/'+o.data.order.id+'/cancel','POST',{version:d.data.order.version,reason:'qa'},c.headers);const q=await fx.call('/api/staff/paid-labels','GET',null,k.headers);const jobs=q.data.jobs.filter(x=>x.order.id===o.data.order.id);assert.deepEqual(jobs.map(x=>x.kind),['CANCEL']);fx.db.close()});
test('PRINT cancellation ticket can be claimed and marked SENT',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),k=role(fx,'KITCHEN'),o=await qrOrder(fx),d=await detail(fx,c,o.data.order.id);await fx.call('/api/staff/orders/'+o.data.order.id+'/cancel','POST',{version:d.data.order.version,reason:'qa'},c.headers);const cancel=fx.db.prepare("select id from pos_kitchen_jobs where order_id=? and kind='CANCEL'").get(o.data.order.id);assert.equal((await fx.call('/api/staff/jobs/'+encodeURIComponent(cancel.id)+'/claim','POST',{},k.headers)).status,200);assert.equal((await fx.call('/api/staff/jobs/'+encodeURIComponent(cancel.id)+'/status','POST',{status:'SENT'},k.headers)).status,200);fx.db.close()});
test('PRINT stale NEW ticket cannot be claimed after whole order cancellation',async()=>{const fx=fixture(),c=role(fx,'CASHIER'),k=role(fx,'KITCHEN'),o=await qrOrder(fx),first=fx.db.prepare("select id from pos_kitchen_jobs where order_id=? and kind='NEW'").get(o.data.order.id),d=await detail(fx,c,o.data.order.id);await fx.call('/api/staff/orders/'+o.data.order.id+'/cancel','POST',{version:d.data.order.version,reason:'qa'},c.headers);assert.equal((await fx.call('/api/staff/jobs/'+encodeURIComponent(first.id)+'/claim','POST',{},k.headers)).status,409);fx.db.close()});
test('SHIFT approved swap updates actual schedule owner through trigger',async()=>{const fx=fixture(),m=role(fx,'MANAGER'),c1=role(fx,'CASHIER'),c2=role(fx,'CASHIER'),date=dayPlus(3);const sch=await makeFutureSchedule(fx,m,c1.id,{date});await fx.call('/api/staff/shift-ops/swap','POST',{requestKey:crypto.randomUUID(),scheduleId:sch.data.id,toStaffId:c2.id,reason:'QA swap'},c1.headers);let row=fx.db.prepare('select * from pos_swap_requests order by created_at desc limit 1').get();await fx.call('/api/staff/shift-ops/swap/'+row.id+'/status','POST',{status:'ACCEPTED',version:row.version},c2.headers);row=fx.db.prepare('select * from pos_swap_requests where id=?').get(row.id);const approved=await fx.call('/api/staff/shift-ops/swap/'+row.id+'/status','POST',{status:'APPROVED',version:row.version,note:'ok'},m.headers);assert.equal(approved.status,200);assert.equal(fx.db.prepare('select staff_id from pos_shift_schedules where id=?').get(sch.data.id).staff_id,c2.id);fx.db.close()});
test('OT manager approval changes request status to APPROVED',async()=>{const fx=fixture(),m=role(fx,'MANAGER'),c=role(fx,'CASHIER');await fx.call('/api/staff/shift-ops/ot','POST',{requestKey:crypto.randomUUID(),workDate:dayPlus(2),startTime:'18:00',endTime:'20:00',reason:'QA overtime'},c.headers);let row=fx.db.prepare('select * from pos_ot_requests order by created_at desc limit 1').get();const r=await fx.call('/api/staff/shift-ops/ot/'+row.id+'/status','POST',{status:'APPROVED',version:row.version,note:'approved'},m.headers);assert.equal(r.status,200);assert.equal(fx.db.prepare('select status from pos_ot_requests where id=?').get(row.id).status,'APPROVED');fx.db.close()});
test('ROLE manager handheld navigation exposes menu/price after permission grant',()=>assert.match(STAFF,/\['products','Món & giá \/ 菜品与价格','CATALOG_MANAGE'\]/));
