import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const APP=readFileSync(new URL('../public/assets/app.js',import.meta.url),'utf8');
const CSS=readFileSync(new URL('../public/assets/app.css',import.meta.url),'utf8');
const HTML=readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const MANIFEST=JSON.parse(readFileSync(new URL('../public/manifest.webmanifest',import.meta.url),'utf8'));
const CATALOG=JSON.parse(readFileSync(new URL('../public/catalog.json',import.meta.url),'utf8'));
const WORKER=readFileSync(new URL('../src/worker.js',import.meta.url),'utf8');
const SW=readFileSync(new URL('../public/sw.js',import.meta.url),'utf8');

const cases=[];
const q=(id,name,fn)=>cases.push([id,name,fn]);
q('Q01','QR HTML declares zh-CN as the primary document language',()=>assert.match(HTML,/<html lang="zh-CN">/));
q('Q02','QR page title identifies Chinese scan ordering',()=>assert.match(HTML,/<title>[^<]*发财扫码点餐/));
q('Q03','PWA manifest language is zh-CN',()=>assert.equal(MANIFEST.lang,'zh-CN'));
q('Q04','PWA short name is Chinese customer-facing brand',()=>assert.equal(MANIFEST.short_name,'发财烧腊'));
q('Q05','Chinese bilingual line has the same font size as Vietnamese',()=>assert.match(CSS,/\.bi-zh\{font-size:1em;/));
q('Q06','Chinese bilingual line is not visually faded',()=>assert.match(CSS,/\.bi-zh\{[^}]*opacity:1/));
q('Q07','Chinese product name uses same base font size as Vietnamese product name',()=>{assert.match(CSS,/\.product h3\{font-size:13px/);assert.match(CSS,/\.product \.cn\{font-size:13px/)});
q('Q08','Chinese toast line keeps full-sized text',()=>assert.match(CSS,/\.toast span\+span\{font-size:1em;opacity:1/));
q('Q09','menu search placeholder is bilingual',()=>assert.match(APP,/placeholder="\$\{esc\(t\('find'\)\)\}"/));
q('Q10','voucher placeholder is bilingual',()=>assert.match(APP,/placeholder="\$\{esc\(t\('voucherPlaceholder'\)\)\}"/));
q('Q11','order-note placeholder is bilingual',()=>assert.match(APP,/placeholder="\$\{esc\(t\('orderNotePlaceholder'\)\)\}"/));
q('Q12','item-note placeholder is bilingual',()=>assert.match(APP,/placeholder="\$\{esc\(t\('notePlaceholder'\)\)\}"/));
q('Q13','member name placeholder contains Chinese example',()=>assert.match(APP,/姓名，例如：王小明/));
q('Q14','member phone placeholder includes Chinese',()=>assert.match(APP,/手机号 \/ SĐT/));
q('Q15','missing-product cart fallback is bilingual',()=>assert.match(APP,/bi\('missingProduct'\)/));
q('Q16','remove-from-cart fallback is bilingual',()=>assert.match(APP,/bi\('removeCart'\)/));
q('Q17','tax display uses bilingual tax labels',()=>{assert.match(APP,/taxExtra:'加收税费'/);assert.match(APP,/taxIncluded:'已含税费'/)});
q('Q18','paid confirmation has Chinese customer message',()=>assert.match(APP,/paymentConfirmed:'店员已确认收款。'/));
q('Q19','kitchen submission confirmation has Chinese customer message',()=>assert.match(APP,/sentKitchen:'订单已发送到厨房。'/));
q('Q20','pay-later flow explicitly tells Chinese customer to call handheld POS staff',()=>assert.match(APP,/payLater:'先点餐 · 用餐后请叫店员携手持POS到桌边结账。'/));
q('Q21','Chinese guide step 1 explains table selection',()=>assert.match(APP,/guide1:'1\. 扫码进入后，先选择您当前所在的正确桌号。'/));
q('Q22','Chinese guide step 2 explains modifiers and cart check',()=>assert.match(APP,/guide2:'2\. 选择菜品、份量、辣度和其他选项，并核对购物车。'/));
q('Q23','Chinese guide step 3 explains order code and kitchen job',()=>assert.match(APP,/guide3:'3\. 点击“确认点餐”后，只有看到订单编号才代表提交成功；系统会立即生成厨房单。'/));
q('Q24','Chinese guide step 4 explains staff payment flow',()=>assert.match(APP,/guide4:'4\. 用餐后请叫店员携手持POS到桌边；店员核对桌号与订单后，再选择现金或银行转账收款。'/));
q('Q25','Chinese help text states payment is not performed on QR UI',()=>assert.match(APP,/serviceText:'本页面只用于点餐，不在这里付款。/));
q('Q26','Chinese member title is customer friendly',()=>assert.match(APP,/memberTitle:'会员中心'/));
q('Q27','Chinese member prompt explains benefits',()=>assert.match(APP,/memberPrompt:'登录或注册会员，可使用会员优惠并累计积分。'/));
q('Q28','Chinese member info says points post only after staff payment confirmation',()=>assert.match(APP,/memberInfo:'会员积分仅在店员确认收款后入账。'/));
q('Q29','member total-spend label is bilingual',()=>assert.match(APP,/bi\('totalSpend'\)/));
q('Q30','member points-history label is bilingual',()=>assert.match(APP,/bi\('pointsHistory'\)/));
q('Q31','password form labels current password bilingually',()=>assert.match(APP,/bi\('currentPassword'\)/));
q('Q32','password API error combines Vietnamese and Chinese backend messages',()=>assert.match(APP,/v\.message&&v\.messageCn\?v\.message\+' \/ '\+v\.messageCn/));
q('Q33','password-change success uses bilingual translation key',()=>assert.match(APP,/toast\(t\('passwordChanged'\)\)/));
q('Q34','selected modifier labels preserve Chinese option name',()=>assert.match(APP,/\[o\.name,o\.nameCn\]\.filter\(Boolean\)\.join\(' \/ '\)/));
q('Q35','downloadable receipt contains Chinese receipt title',()=>assert.match(APP,/点餐确认单/));
q('Q36','downloadable receipt contains Chinese paid and unpaid states',()=>{assert.match(APP,/已付款/);assert.match(APP,/未付款/)});
q('Q37','table picker Chinese wording is explicit',()=>assert.match(APP,/selectTable:'请选择您所在的桌号'/));
q('Q38','takeaway wording is clear for Chinese customer',()=>assert.match(APP,/takeaway:'打包带走'/));
q('Q39','all PHAT TAI catalog products have a Chinese name',()=>{assert.ok(CATALOG.products.length>=13);for(const p of CATALOG.products)assert.ok(String(p.nameCn||'').trim().length>=2,p.sku)});
q('Q40','worker customer-facing error table contains Chinese translations',()=>{for(const key of ['INVALID_TABLE','INVALID_CART','INVALID_ITEM','UNAVAILABLE_PRODUCT','INVALID_QUANTITY','INVALID_MODIFIERS','INVALID_SIZE','INVALID_SPICE','ORDER_NOT_CONFIRMED','ORDER_NOT_FOUND','MEMBER_LOGIN_FAILED','INVALID_VOUCHER','VOUCHER_MIN','VOUCHER_FULL','OUT_OF_STOCK'])assert.match(WORKER,new RegExp(key+":\\[[^\\]]*'[^']*[\\u3400-\\u9fff][^']*'"),key)});
q('Q41','service worker cache key bumped for QR Chinese release',()=>assert.match(SW,/phattai\.9-20260929/));
q('Q42','root language is switched to zh-CN at runtime',()=>assert.match(APP,/document\.documentElement\.lang='zh-CN'/));
q('Q43','Chinese order-failure copy warns not to modify and duplicate-submit uncertain order',()=>assert.match(APP,/orderFail:'服务器尚未确认订单。购物车已保留，请不要重复修改/));
q('Q44','Chinese receipt note clearly says it is not proof of payment',()=>assert.match(APP,/receiptNote:'此单仅供核对，不是税务发票，也不是已付款证明。'/));
q('Q45','Chinese voucher reservation wording matches pay-later business flow',()=>assert.match(APP,/voucherReserved:'优惠在订单提交时预留，店员确认付款后才计入已使用。'/));
q('Q46','Chinese payment status label is explicit',()=>assert.match(APP,/payment:'付款状态'/));
q('Q47','Chinese unpaid label says staff settles at table',()=>assert.match(APP,/unpaid:'未付款 · 用餐后由店员到桌边结账'/));
q('Q48','Chinese another-order action means add more items',()=>assert.match(APP,/another:'继续加点'/));
q('Q49','Chinese loading and retry text exist',()=>{assert.match(APP,/loading:'正在加载菜单…'/);assert.match(APP,/retry:'重新连接'/)});
q('Q50','Chinese final-price explanation refers to server calculation',()=>assert.match(APP,/priceMayChange:'最终价格以下单时服务器核算结果为准。'/));

for(const [id,name,fn] of cases)test(`${id} ${name}`,fn);
assert.equal(cases.length,50);
